//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIAC.ActivarVOLTE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews", ConfigurationName="SIAC.ActivarVOLTE.ActivarVOLTEWSPortType")]
    public interface ActivarVOLTEWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación activaTecVolte no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/activavoltews/consultar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1 activaTecVolte(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/activavoltews/consultar", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1> activaTecVolteAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarTecVoLTE no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/activavoltews/consultarTecVoLTE", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1 consultarTecVoLTE(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventa/activavoltews/consultarTecVoLTE", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1> consultarTecVoLTEAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types")]
    public partial class activaTecVolteRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string iccidSimActualField;
        
        private string iccidSimNuevoField;
        
        private string coIdField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string iccidSimActual {
            get {
                return this.iccidSimActualField;
            }
            set {
                this.iccidSimActualField = value;
                this.RaisePropertyChanged("iccidSimActual");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iccidSimNuevo {
            get {
                return this.iccidSimNuevoField;
            }
            set {
                this.iccidSimNuevoField = value;
                this.RaisePropertyChanged("iccidSimNuevo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class parametrosTypeObjetoOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types")]
    public partial class activaTecVolteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private string tecnologiasActivadasField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tecnologiasActivadas {
            get {
                return this.tecnologiasActivadasField;
            }
            set {
                this.tecnologiasActivadasField = value;
                this.RaisePropertyChanged("tecnologiasActivadas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activaTecVolteRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest activaTecVolteRequest;
        
        public activaTecVolteRequest1() {
        }
        
        public activaTecVolteRequest1(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest activaTecVolteRequest) {
            this.activaTecVolteRequest = activaTecVolteRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class activaTecVolteResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse activaTecVolteResponse;
        
        public activaTecVolteResponse1() {
        }
        
        public activaTecVolteResponse1(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse activaTecVolteResponse) {
            this.activaTecVolteResponse = activaTecVolteResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types")]
    public partial class consultarTecVoLTERequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string serieVOLTEField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serieVOLTE {
            get {
                return this.serieVOLTEField;
            }
            set {
                this.serieVOLTEField = value;
                this.RaisePropertyChanged("serieVOLTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types")]
    public partial class consultarTecVoLTEResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private string codigoMaterialField;
        
        private string existeChipField;
        
        private string autenticaVOLTEField;
        
        private string codigoResultadoField;
        
        private string mensajeResultadoField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
                this.RaisePropertyChanged("codigoMaterial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string existeChip {
            get {
                return this.existeChipField;
            }
            set {
                this.existeChipField = value;
                this.RaisePropertyChanged("existeChip");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string autenticaVOLTE {
            get {
                return this.autenticaVOLTEField;
            }
            set {
                this.autenticaVOLTEField = value;
                this.RaisePropertyChanged("autenticaVOLTE");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codigoResultado {
            get {
                return this.codigoResultadoField;
            }
            set {
                this.codigoResultadoField = value;
                this.RaisePropertyChanged("codigoResultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string mensajeResultado {
            get {
                return this.mensajeResultadoField;
            }
            set {
                this.mensajeResultadoField = value;
                this.RaisePropertyChanged("mensajeResultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTecVoLTERequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest consultarTecVoLTERequest;
        
        public consultarTecVoLTERequest1() {
        }
        
        public consultarTecVoLTERequest1(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest consultarTecVoLTERequest) {
            this.consultarTecVoLTERequest = consultarTecVoLTERequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarTecVoLTEResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/activavoltews/types", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse consultarTecVoLTEResponse;
        
        public consultarTecVoLTEResponse1() {
        }
        
        public consultarTecVoLTEResponse1(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse consultarTecVoLTEResponse) {
            this.consultarTecVoLTEResponse = consultarTecVoLTEResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActivarVOLTEWSPortTypeChannel : Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActivarVOLTEWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType>, Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType {
        
        public ActivarVOLTEWSPortTypeClient() {
        }
        
        public ActivarVOLTEWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActivarVOLTEWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivarVOLTEWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActivarVOLTEWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1 Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType.activaTecVolte(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 request) {
            return base.Channel.activaTecVolte(request);
        }
        
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse activaTecVolte(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest activaTecVolteRequest) {
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1();
            inValue.activaTecVolteRequest = activaTecVolteRequest;
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1 retVal = ((Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType)(this)).activaTecVolte(inValue);
            return retVal.activaTecVolteResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1> Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType.activaTecVolteAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 request) {
            return base.Channel.activaTecVolteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteResponse1> activaTecVolteAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest activaTecVolteRequest) {
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.activaTecVolteRequest1();
            inValue.activaTecVolteRequest = activaTecVolteRequest;
            return ((Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType)(this)).activaTecVolteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1 Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType.consultarTecVoLTE(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 request) {
            return base.Channel.consultarTecVoLTE(request);
        }
        
        public Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse consultarTecVoLTE(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest consultarTecVoLTERequest) {
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1();
            inValue.consultarTecVoLTERequest = consultarTecVoLTERequest;
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1 retVal = ((Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType)(this)).consultarTecVoLTE(inValue);
            return retVal.consultarTecVoLTEResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1> Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType.consultarTecVoLTEAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 request) {
            return base.Channel.consultarTecVoLTEAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTEResponse1> consultarTecVoLTEAsync(Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest consultarTecVoLTERequest) {
            Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.consultarTecVoLTERequest1();
            inValue.consultarTecVoLTERequest = consultarTecVoLTERequest;
            return ((Claro.SIACU.ProxyService.SIAC.ActivarVOLTE.ActivarVOLTEWSPortType)(this)).consultarTecVoLTEAsync(inValue);
        }
    }
}
