//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPre.Service2
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://pe/com/claro/esb/services/consultaPrepago/ws", ConfigurationName="SIACPre.Service2.EbsDatosPrepagoV2")]
    public interface EbsDatosPrepagoV2 {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://pe/com/claro/esb/services/schemas/InDatosPrepago) no coincide con el valor predeterminado (http://pe/com/claro/esb/services/consultaPrepago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="INDatosPrepagoResponse")]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoResponse leerDatosPrepago(Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://pe/com/claro/esb/services/schemas/EstadoSuscripcion) no coincide con el valor predeterminado (http://pe/com/claro/esb/services/consultaPrepago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="EstadoSuscripcionResponse")]
        Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionResponse consultaEstadoSuscripcion(Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://pe/com/claro/esb/services/schemas/InDatosPrepago) no coincide con el valor predeterminado (http://pe/com/claro/esb/services/consultaPrepago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="INDatosLineaResponse")]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoResponse leerEstado(Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje (http://pe/com/claro/esb/services/schemas/InSaldoBolsas) no coincide con el valor predeterminado (http://pe/com/claro/esb/services/consultaPrepago/ws).
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="INSaldosBolsasResponse")]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasResponse leerSaldosBolsas(Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class INDatosPrepagoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public partial class SaldosBolsas : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string isFirstCalledField;
        
        private string isLockedField;
        
        private string expiryDateField;
        
        private string deletionDateField;
        
        private string onPeakAccountIdBalanceField;
        
        private string onPeakAccountIdExpiryDateField;
        
        private string smsPromoAccountIdBalanceField;
        
        private string smsPromoAccountIdExpiryDateField;
        
        private string voice1PromoAccountIdBalanceField;
        
        private string voice1PromoAccountIdExpiryDateField;
        
        private string voice2PromoAccountIdBalanceField;
        
        private string voice2PromoAccountIdExpiryDateField;
        
        private string gprsPromoAccountIdBalanceField;
        
        private string gprsPromoAccountIdExpiryDateField;
        
        private string mmsPromoAccountIdBalanceField;
        
        private string mmsPromoAccountIdExpiryDateField;
        
        private string bonusPromoAccountIdBalanceField;
        
        private string bonusPromoAccountIdExpiryDateField;
        
        private string smsLoyaltyAccountIdBalanceField;
        
        private string smsLoyaltyAccountIdExpiryDateField;
        
        private string voiceLoyaltyAccountIdBalanceField;
        
        private string voiceLoyaltyAccountIdExpiryDateField;
        
        private string gprsLoyaltyAccountIdBalanceField;
        
        private string gprsLoyaltyAccountIdExpiryDateField;
        
        private string mmsLoyaltyAccountIdBalanceField;
        
        private string mmsLoyaltyAccountIdExpiryDateField;
        
        private string bonusCounter_Account52BalanceField;
        
        private string bonusCounter_Account52ExpiryDateField;
        
        private string bonusCounter_Account54BalanceField;
        
        private string bonusCounter_Account54ExpiryDateField;
        
        private string bonusCounter_Account57BalanceField;
        
        private string bonusCounter_Account57ExpiryDateField;
        
        private string bonusCounter_Account58BalanceField;
        
        private string bonusCounter_Account58ExpiryDateField;
        
        private string isSelectField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string isFirstCalled {
            get {
                return this.isFirstCalledField;
            }
            set {
                this.isFirstCalledField = value;
                this.RaisePropertyChanged("isFirstCalled");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string isLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
                this.RaisePropertyChanged("isLocked");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string deletionDate {
            get {
                return this.deletionDateField;
            }
            set {
                this.deletionDateField = value;
                this.RaisePropertyChanged("deletionDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string onPeakAccountIdBalance {
            get {
                return this.onPeakAccountIdBalanceField;
            }
            set {
                this.onPeakAccountIdBalanceField = value;
                this.RaisePropertyChanged("onPeakAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string onPeakAccountIdExpiryDate {
            get {
                return this.onPeakAccountIdExpiryDateField;
            }
            set {
                this.onPeakAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("onPeakAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string smsPromoAccountIdBalance {
            get {
                return this.smsPromoAccountIdBalanceField;
            }
            set {
                this.smsPromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("smsPromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string smsPromoAccountIdExpiryDate {
            get {
                return this.smsPromoAccountIdExpiryDateField;
            }
            set {
                this.smsPromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("smsPromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string voice1PromoAccountIdBalance {
            get {
                return this.voice1PromoAccountIdBalanceField;
            }
            set {
                this.voice1PromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("voice1PromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string voice1PromoAccountIdExpiryDate {
            get {
                return this.voice1PromoAccountIdExpiryDateField;
            }
            set {
                this.voice1PromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("voice1PromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string voice2PromoAccountIdBalance {
            get {
                return this.voice2PromoAccountIdBalanceField;
            }
            set {
                this.voice2PromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("voice2PromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string voice2PromoAccountIdExpiryDate {
            get {
                return this.voice2PromoAccountIdExpiryDateField;
            }
            set {
                this.voice2PromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("voice2PromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string gprsPromoAccountIdBalance {
            get {
                return this.gprsPromoAccountIdBalanceField;
            }
            set {
                this.gprsPromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("gprsPromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string gprsPromoAccountIdExpiryDate {
            get {
                return this.gprsPromoAccountIdExpiryDateField;
            }
            set {
                this.gprsPromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("gprsPromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string mmsPromoAccountIdBalance {
            get {
                return this.mmsPromoAccountIdBalanceField;
            }
            set {
                this.mmsPromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("mmsPromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string mmsPromoAccountIdExpiryDate {
            get {
                return this.mmsPromoAccountIdExpiryDateField;
            }
            set {
                this.mmsPromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("mmsPromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string bonusPromoAccountIdBalance {
            get {
                return this.bonusPromoAccountIdBalanceField;
            }
            set {
                this.bonusPromoAccountIdBalanceField = value;
                this.RaisePropertyChanged("bonusPromoAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string bonusPromoAccountIdExpiryDate {
            get {
                return this.bonusPromoAccountIdExpiryDateField;
            }
            set {
                this.bonusPromoAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("bonusPromoAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string smsLoyaltyAccountIdBalance {
            get {
                return this.smsLoyaltyAccountIdBalanceField;
            }
            set {
                this.smsLoyaltyAccountIdBalanceField = value;
                this.RaisePropertyChanged("smsLoyaltyAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string smsLoyaltyAccountIdExpiryDate {
            get {
                return this.smsLoyaltyAccountIdExpiryDateField;
            }
            set {
                this.smsLoyaltyAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("smsLoyaltyAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string voiceLoyaltyAccountIdBalance {
            get {
                return this.voiceLoyaltyAccountIdBalanceField;
            }
            set {
                this.voiceLoyaltyAccountIdBalanceField = value;
                this.RaisePropertyChanged("voiceLoyaltyAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string voiceLoyaltyAccountIdExpiryDate {
            get {
                return this.voiceLoyaltyAccountIdExpiryDateField;
            }
            set {
                this.voiceLoyaltyAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("voiceLoyaltyAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string gprsLoyaltyAccountIdBalance {
            get {
                return this.gprsLoyaltyAccountIdBalanceField;
            }
            set {
                this.gprsLoyaltyAccountIdBalanceField = value;
                this.RaisePropertyChanged("gprsLoyaltyAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string gprsLoyaltyAccountIdExpiryDate {
            get {
                return this.gprsLoyaltyAccountIdExpiryDateField;
            }
            set {
                this.gprsLoyaltyAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("gprsLoyaltyAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string mmsLoyaltyAccountIdBalance {
            get {
                return this.mmsLoyaltyAccountIdBalanceField;
            }
            set {
                this.mmsLoyaltyAccountIdBalanceField = value;
                this.RaisePropertyChanged("mmsLoyaltyAccountIdBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string mmsLoyaltyAccountIdExpiryDate {
            get {
                return this.mmsLoyaltyAccountIdExpiryDateField;
            }
            set {
                this.mmsLoyaltyAccountIdExpiryDateField = value;
                this.RaisePropertyChanged("mmsLoyaltyAccountIdExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string bonusCounter_Account52Balance {
            get {
                return this.bonusCounter_Account52BalanceField;
            }
            set {
                this.bonusCounter_Account52BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account52Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string bonusCounter_Account52ExpiryDate {
            get {
                return this.bonusCounter_Account52ExpiryDateField;
            }
            set {
                this.bonusCounter_Account52ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account52ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string bonusCounter_Account54Balance {
            get {
                return this.bonusCounter_Account54BalanceField;
            }
            set {
                this.bonusCounter_Account54BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account54Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string bonusCounter_Account54ExpiryDate {
            get {
                return this.bonusCounter_Account54ExpiryDateField;
            }
            set {
                this.bonusCounter_Account54ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account54ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string bonusCounter_Account57Balance {
            get {
                return this.bonusCounter_Account57BalanceField;
            }
            set {
                this.bonusCounter_Account57BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account57Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string bonusCounter_Account57ExpiryDate {
            get {
                return this.bonusCounter_Account57ExpiryDateField;
            }
            set {
                this.bonusCounter_Account57ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account57ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string bonusCounter_Account58Balance {
            get {
                return this.bonusCounter_Account58BalanceField;
            }
            set {
                this.bonusCounter_Account58BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account58Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string bonusCounter_Account58ExpiryDate {
            get {
                return this.bonusCounter_Account58ExpiryDateField;
            }
            set {
                this.bonusCounter_Account58ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account58ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string isSelect {
            get {
                return this.isSelectField;
            }
            set {
                this.isSelectField = value;
                this.RaisePropertyChanged("isSelect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class DatosLinea : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string providerIDField;
        
        private string isFirstCallPassedField;
        
        private string isLockedField;
        
        private string subscriberLifeCycleStatusField;
        
        private string subscriberStatusField;
        
        private string expiryDateField;
        
        private string deletionDateField;
        
        private string isSelectField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string providerID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("providerID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string isFirstCallPassed {
            get {
                return this.isFirstCallPassedField;
            }
            set {
                this.isFirstCallPassedField = value;
                this.RaisePropertyChanged("isFirstCallPassed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string isLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
                this.RaisePropertyChanged("isLocked");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string subscriberLifeCycleStatus {
            get {
                return this.subscriberLifeCycleStatusField;
            }
            set {
                this.subscriberLifeCycleStatusField = value;
                this.RaisePropertyChanged("subscriberLifeCycleStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string subscriberStatus {
            get {
                return this.subscriberStatusField;
            }
            set {
                this.subscriberStatusField = value;
                this.RaisePropertyChanged("subscriberStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string deletionDate {
            get {
                return this.deletionDateField;
            }
            set {
                this.deletionDateField = value;
                this.RaisePropertyChanged("deletionDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string isSelect {
            get {
                return this.isSelectField;
            }
            set {
                this.isSelectField = value;
                this.RaisePropertyChanged("isSelect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class DatosPrepago : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerIDField;
        
        private string cgpaField;
        
        private string providerIDField;
        
        private string useTestEnvironmentField;
        
        private string activeFnFOptionField;
        
        private string isLockedField;
        
        private string isLockedForPeriodicRechargeField;
        
        private string planGroupIDField;
        
        private string isFirstCallPassedField;
        
        private string subscriberLifeCycleStatusField;
        
        private string firstCallDateField;
        
        private string rechargingPeriodField;
        
        private string expiryDateField;
        
        private string deletionDateField;
        
        private string isFnFPossibleField;
        
        private string userGroup0Field;
        
        private string userGroup1Field;
        
        private DatosPrepagoFnfNumber[] fnfNumberField;
        
        private string tariffModelNumberField;
        
        private string postpaidField;
        
        private string subscriberStatusField;
        
        private string subscriberLastStatusField;
        
        private string statusChangeDateField;
        
        private string onPeakAccountIDBalanceField;
        
        private string onPeakAccountIDExpiryDateField;
        
        private string sMSLoyaltyAccountIDBalanceField;
        
        private string sMSLoyaltyAccountIDExpiryDateField;
        
        private string voiceLoyaltyAccountIDBalanceField;
        
        private string voiceLoyaltyAccountIDExpiryDateField;
        
        private string gPRSLoyaltyAccountIDBalanceField;
        
        private string gPRSLoyaltyAccountIDExpiryDateField;
        
        private string sMSPromoAccountIDBalanceField;
        
        private string sMSPromoAccountIDExpiryDateField;
        
        private string voice1PromoAccountIDBalanceField;
        
        private string voice1PromoAccountIDExpiryDateField;
        
        private string voice2PromoAccountIDBalanceField;
        
        private string voice2PromoAccountIDExpiryDateField;
        
        private string gPRSPromoAccountIDBalanceField;
        
        private string gPRSPromoAccountIDExpiryDateField;
        
        private string bonusPromoAccountIDBalanceField;
        
        private string bonusPromoAccountIDExpiryDateField;
        
        private string mMSLoyaltyAccountIDBalanceField;
        
        private string mMSLoyaltyAccountIDExpiryDateField;
        
        private string mMSPromoAccountIDBalanceField;
        
        private string mMSPromoAccountIDExpiryDateField;
        
        private string bonusCounter_Account52BalanceField;
        
        private string bonusCounter_Account52ExpiryDateField;
        
        private string bonusCounter_Account54BalanceField;
        
        private string bonusCounter_Account54ExpiryDateField;
        
        private string bonusCounter_Account57BalanceField;
        
        private string bonusCounter_Account57ExpiryDateField;
        
        private string bonusCounter_Account58BalanceField;
        
        private string bonusCounter_Account58ExpiryDateField;
        
        private string voucherRchFraudCounterField;
        
        private string counterChangeFnFnoForFreeField;
        
        private string counterChangeFAnoForFreeField;
        
        private string counterChangeHZInoForFreeField;
        
        private string counterSubscribeFAForFreeField;
        
        private string counterSubscribeFnFForFreeField;
        
        private string counterSubscribeHZIForFreeField;
        
        private string counterSubscribeMLCForFreeField;
        
        private string counterChangeTariffForFreeField;
        
        private string cNTNumberField;
        
        private string isCNTPossibleField;
        
        private string imsiField;
        
        private string isSelectField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string customerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
                this.RaisePropertyChanged("customerID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cgpa {
            get {
                return this.cgpaField;
            }
            set {
                this.cgpaField = value;
                this.RaisePropertyChanged("cgpa");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string providerID {
            get {
                return this.providerIDField;
            }
            set {
                this.providerIDField = value;
                this.RaisePropertyChanged("providerID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string useTestEnvironment {
            get {
                return this.useTestEnvironmentField;
            }
            set {
                this.useTestEnvironmentField = value;
                this.RaisePropertyChanged("useTestEnvironment");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string activeFnFOption {
            get {
                return this.activeFnFOptionField;
            }
            set {
                this.activeFnFOptionField = value;
                this.RaisePropertyChanged("activeFnFOption");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string isLocked {
            get {
                return this.isLockedField;
            }
            set {
                this.isLockedField = value;
                this.RaisePropertyChanged("isLocked");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string isLockedForPeriodicRecharge {
            get {
                return this.isLockedForPeriodicRechargeField;
            }
            set {
                this.isLockedForPeriodicRechargeField = value;
                this.RaisePropertyChanged("isLockedForPeriodicRecharge");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string planGroupID {
            get {
                return this.planGroupIDField;
            }
            set {
                this.planGroupIDField = value;
                this.RaisePropertyChanged("planGroupID");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string isFirstCallPassed {
            get {
                return this.isFirstCallPassedField;
            }
            set {
                this.isFirstCallPassedField = value;
                this.RaisePropertyChanged("isFirstCallPassed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string subscriberLifeCycleStatus {
            get {
                return this.subscriberLifeCycleStatusField;
            }
            set {
                this.subscriberLifeCycleStatusField = value;
                this.RaisePropertyChanged("subscriberLifeCycleStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string firstCallDate {
            get {
                return this.firstCallDateField;
            }
            set {
                this.firstCallDateField = value;
                this.RaisePropertyChanged("firstCallDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string rechargingPeriod {
            get {
                return this.rechargingPeriodField;
            }
            set {
                this.rechargingPeriodField = value;
                this.RaisePropertyChanged("rechargingPeriod");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string deletionDate {
            get {
                return this.deletionDateField;
            }
            set {
                this.deletionDateField = value;
                this.RaisePropertyChanged("deletionDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string isFnFPossible {
            get {
                return this.isFnFPossibleField;
            }
            set {
                this.isFnFPossibleField = value;
                this.RaisePropertyChanged("isFnFPossible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string userGroup0 {
            get {
                return this.userGroup0Field;
            }
            set {
                this.userGroup0Field = value;
                this.RaisePropertyChanged("userGroup0");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string userGroup1 {
            get {
                return this.userGroup1Field;
            }
            set {
                this.userGroup1Field = value;
                this.RaisePropertyChanged("userGroup1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("fnfNumber", Order=17)]
        public DatosPrepagoFnfNumber[] fnfNumber {
            get {
                return this.fnfNumberField;
            }
            set {
                this.fnfNumberField = value;
                this.RaisePropertyChanged("fnfNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string tariffModelNumber {
            get {
                return this.tariffModelNumberField;
            }
            set {
                this.tariffModelNumberField = value;
                this.RaisePropertyChanged("tariffModelNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string postpaid {
            get {
                return this.postpaidField;
            }
            set {
                this.postpaidField = value;
                this.RaisePropertyChanged("postpaid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string subscriberStatus {
            get {
                return this.subscriberStatusField;
            }
            set {
                this.subscriberStatusField = value;
                this.RaisePropertyChanged("subscriberStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string subscriberLastStatus {
            get {
                return this.subscriberLastStatusField;
            }
            set {
                this.subscriberLastStatusField = value;
                this.RaisePropertyChanged("subscriberLastStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string statusChangeDate {
            get {
                return this.statusChangeDateField;
            }
            set {
                this.statusChangeDateField = value;
                this.RaisePropertyChanged("statusChangeDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string onPeakAccountIDBalance {
            get {
                return this.onPeakAccountIDBalanceField;
            }
            set {
                this.onPeakAccountIDBalanceField = value;
                this.RaisePropertyChanged("onPeakAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string onPeakAccountIDExpiryDate {
            get {
                return this.onPeakAccountIDExpiryDateField;
            }
            set {
                this.onPeakAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("onPeakAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string sMSLoyaltyAccountIDBalance {
            get {
                return this.sMSLoyaltyAccountIDBalanceField;
            }
            set {
                this.sMSLoyaltyAccountIDBalanceField = value;
                this.RaisePropertyChanged("sMSLoyaltyAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string sMSLoyaltyAccountIDExpiryDate {
            get {
                return this.sMSLoyaltyAccountIDExpiryDateField;
            }
            set {
                this.sMSLoyaltyAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("sMSLoyaltyAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string voiceLoyaltyAccountIDBalance {
            get {
                return this.voiceLoyaltyAccountIDBalanceField;
            }
            set {
                this.voiceLoyaltyAccountIDBalanceField = value;
                this.RaisePropertyChanged("voiceLoyaltyAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string voiceLoyaltyAccountIDExpiryDate {
            get {
                return this.voiceLoyaltyAccountIDExpiryDateField;
            }
            set {
                this.voiceLoyaltyAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("voiceLoyaltyAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string gPRSLoyaltyAccountIDBalance {
            get {
                return this.gPRSLoyaltyAccountIDBalanceField;
            }
            set {
                this.gPRSLoyaltyAccountIDBalanceField = value;
                this.RaisePropertyChanged("gPRSLoyaltyAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string gPRSLoyaltyAccountIDExpiryDate {
            get {
                return this.gPRSLoyaltyAccountIDExpiryDateField;
            }
            set {
                this.gPRSLoyaltyAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("gPRSLoyaltyAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string sMSPromoAccountIDBalance {
            get {
                return this.sMSPromoAccountIDBalanceField;
            }
            set {
                this.sMSPromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("sMSPromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string sMSPromoAccountIDExpiryDate {
            get {
                return this.sMSPromoAccountIDExpiryDateField;
            }
            set {
                this.sMSPromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("sMSPromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string voice1PromoAccountIDBalance {
            get {
                return this.voice1PromoAccountIDBalanceField;
            }
            set {
                this.voice1PromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("voice1PromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string voice1PromoAccountIDExpiryDate {
            get {
                return this.voice1PromoAccountIDExpiryDateField;
            }
            set {
                this.voice1PromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("voice1PromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string voice2PromoAccountIDBalance {
            get {
                return this.voice2PromoAccountIDBalanceField;
            }
            set {
                this.voice2PromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("voice2PromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string voice2PromoAccountIDExpiryDate {
            get {
                return this.voice2PromoAccountIDExpiryDateField;
            }
            set {
                this.voice2PromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("voice2PromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string gPRSPromoAccountIDBalance {
            get {
                return this.gPRSPromoAccountIDBalanceField;
            }
            set {
                this.gPRSPromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("gPRSPromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string gPRSPromoAccountIDExpiryDate {
            get {
                return this.gPRSPromoAccountIDExpiryDateField;
            }
            set {
                this.gPRSPromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("gPRSPromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string bonusPromoAccountIDBalance {
            get {
                return this.bonusPromoAccountIDBalanceField;
            }
            set {
                this.bonusPromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("bonusPromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string bonusPromoAccountIDExpiryDate {
            get {
                return this.bonusPromoAccountIDExpiryDateField;
            }
            set {
                this.bonusPromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("bonusPromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string mMSLoyaltyAccountIDBalance {
            get {
                return this.mMSLoyaltyAccountIDBalanceField;
            }
            set {
                this.mMSLoyaltyAccountIDBalanceField = value;
                this.RaisePropertyChanged("mMSLoyaltyAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string mMSLoyaltyAccountIDExpiryDate {
            get {
                return this.mMSLoyaltyAccountIDExpiryDateField;
            }
            set {
                this.mMSLoyaltyAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("mMSLoyaltyAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string mMSPromoAccountIDBalance {
            get {
                return this.mMSPromoAccountIDBalanceField;
            }
            set {
                this.mMSPromoAccountIDBalanceField = value;
                this.RaisePropertyChanged("mMSPromoAccountIDBalance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string mMSPromoAccountIDExpiryDate {
            get {
                return this.mMSPromoAccountIDExpiryDateField;
            }
            set {
                this.mMSPromoAccountIDExpiryDateField = value;
                this.RaisePropertyChanged("mMSPromoAccountIDExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string bonusCounter_Account52Balance {
            get {
                return this.bonusCounter_Account52BalanceField;
            }
            set {
                this.bonusCounter_Account52BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account52Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string bonusCounter_Account52ExpiryDate {
            get {
                return this.bonusCounter_Account52ExpiryDateField;
            }
            set {
                this.bonusCounter_Account52ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account52ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string bonusCounter_Account54Balance {
            get {
                return this.bonusCounter_Account54BalanceField;
            }
            set {
                this.bonusCounter_Account54BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account54Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string bonusCounter_Account54ExpiryDate {
            get {
                return this.bonusCounter_Account54ExpiryDateField;
            }
            set {
                this.bonusCounter_Account54ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account54ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string bonusCounter_Account57Balance {
            get {
                return this.bonusCounter_Account57BalanceField;
            }
            set {
                this.bonusCounter_Account57BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account57Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string bonusCounter_Account57ExpiryDate {
            get {
                return this.bonusCounter_Account57ExpiryDateField;
            }
            set {
                this.bonusCounter_Account57ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account57ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string bonusCounter_Account58Balance {
            get {
                return this.bonusCounter_Account58BalanceField;
            }
            set {
                this.bonusCounter_Account58BalanceField = value;
                this.RaisePropertyChanged("bonusCounter_Account58Balance");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string bonusCounter_Account58ExpiryDate {
            get {
                return this.bonusCounter_Account58ExpiryDateField;
            }
            set {
                this.bonusCounter_Account58ExpiryDateField = value;
                this.RaisePropertyChanged("bonusCounter_Account58ExpiryDate");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string voucherRchFraudCounter {
            get {
                return this.voucherRchFraudCounterField;
            }
            set {
                this.voucherRchFraudCounterField = value;
                this.RaisePropertyChanged("voucherRchFraudCounter");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string counterChangeFnFnoForFree {
            get {
                return this.counterChangeFnFnoForFreeField;
            }
            set {
                this.counterChangeFnFnoForFreeField = value;
                this.RaisePropertyChanged("counterChangeFnFnoForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string counterChangeFAnoForFree {
            get {
                return this.counterChangeFAnoForFreeField;
            }
            set {
                this.counterChangeFAnoForFreeField = value;
                this.RaisePropertyChanged("counterChangeFAnoForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string counterChangeHZInoForFree {
            get {
                return this.counterChangeHZInoForFreeField;
            }
            set {
                this.counterChangeHZInoForFreeField = value;
                this.RaisePropertyChanged("counterChangeHZInoForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string counterSubscribeFAForFree {
            get {
                return this.counterSubscribeFAForFreeField;
            }
            set {
                this.counterSubscribeFAForFreeField = value;
                this.RaisePropertyChanged("counterSubscribeFAForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string counterSubscribeFnFForFree {
            get {
                return this.counterSubscribeFnFForFreeField;
            }
            set {
                this.counterSubscribeFnFForFreeField = value;
                this.RaisePropertyChanged("counterSubscribeFnFForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string counterSubscribeHZIForFree {
            get {
                return this.counterSubscribeHZIForFreeField;
            }
            set {
                this.counterSubscribeHZIForFreeField = value;
                this.RaisePropertyChanged("counterSubscribeHZIForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string counterSubscribeMLCForFree {
            get {
                return this.counterSubscribeMLCForFreeField;
            }
            set {
                this.counterSubscribeMLCForFreeField = value;
                this.RaisePropertyChanged("counterSubscribeMLCForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string counterChangeTariffForFree {
            get {
                return this.counterChangeTariffForFreeField;
            }
            set {
                this.counterChangeTariffForFreeField = value;
                this.RaisePropertyChanged("counterChangeTariffForFree");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string cNTNumber {
            get {
                return this.cNTNumberField;
            }
            set {
                this.cNTNumberField = value;
                this.RaisePropertyChanged("cNTNumber");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string isCNTPossible {
            get {
                return this.isCNTPossibleField;
            }
            set {
                this.isCNTPossibleField = value;
                this.RaisePropertyChanged("isCNTPossible");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
                this.RaisePropertyChanged("imsi");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public string isSelect {
            get {
                return this.isSelectField;
            }
            set {
                this.isSelectField = value;
                this.RaisePropertyChanged("isSelect");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class DatosPrepagoFnfNumber : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string indiceField;
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string indice {
            get {
                return this.indiceField;
            }
            set {
                this.indiceField = value;
                this.RaisePropertyChanged("indice");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class INDatosPrepagoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string resultadoField;
        
        private string transaccionField;
        
        private DatosPrepago datosPrePagoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DatosPrepago datosPrePago {
            get {
                return this.datosPrePagoField;
            }
            set {
                this.datosPrePagoField = value;
                this.RaisePropertyChanged("datosPrePago");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerDatosPrepago", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerDatosPrepagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoRequest INDatosPrepagoRequest;
        
        public leerDatosPrepagoRequest() {
        }
        
        public leerDatosPrepagoRequest(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoRequest INDatosPrepagoRequest) {
            this.INDatosPrepagoRequest = INDatosPrepagoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerDatosPrepagoResponse", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerDatosPrepagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoResponse INDatosPrepagoResponse;
        
        public leerDatosPrepagoResponse() {
        }
        
        public leerDatosPrepagoResponse(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoResponse INDatosPrepagoResponse) {
            this.INDatosPrepagoResponse = INDatosPrepagoResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion")]
    public partial class EstadoSuscripcionRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        private string promocionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string promocion {
            get {
                return this.promocionField;
            }
            set {
                this.promocionField = value;
                this.RaisePropertyChanged("promocion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion")]
    public partial class EstadoSuscripcionResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string resultadoField;
        
        private string mensajeField;
        
        private string transaccionField;
        
        private string statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaEstadoSuscripcion", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class consultaEstadoSuscripcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionRequest EstadoSuscripcionRequest;
        
        public consultaEstadoSuscripcionRequest() {
        }
        
        public consultaEstadoSuscripcionRequest(Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionRequest EstadoSuscripcionRequest) {
            this.EstadoSuscripcionRequest = EstadoSuscripcionRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaEstadoSuscripcionResponse", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class consultaEstadoSuscripcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/EstadoSuscripcion")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionResponse EstadoSuscripcionResponse;
        
        public consultaEstadoSuscripcionResponse() {
        }
        
        public consultaEstadoSuscripcionResponse(Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionResponse EstadoSuscripcionResponse) {
            this.EstadoSuscripcionResponse = EstadoSuscripcionResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class INDatosLineaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public partial class INDatosLineaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mensajeField;
        
        private string resultadoField;
        
        private string transaccionField;
        
        private DatosLinea datosLineaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public DatosLinea datosLinea {
            get {
                return this.datosLineaField;
            }
            set {
                this.datosLineaField = value;
                this.RaisePropertyChanged("datosLinea");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerEstado", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerEstadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaRequest INDatosLineaRequest;
        
        public leerEstadoRequest() {
        }
        
        public leerEstadoRequest(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaRequest INDatosLineaRequest) {
            this.INDatosLineaRequest = INDatosLineaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerEstadoResponse", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerEstadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaResponse INDatosLineaResponse;
        
        public leerEstadoResponse() {
        }
        
        public leerEstadoResponse(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaResponse INDatosLineaResponse) {
            this.INDatosLineaResponse = INDatosLineaResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public partial class INSaldosBolsasRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string telefonoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public partial class INSaldosBolsasResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descripcionField;
        
        private string resultadoField;
        
        private string transaccionField;
        
        private SaldosBolsas saldosBolsasField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
                this.RaisePropertyChanged("resultado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
                this.RaisePropertyChanged("transaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public SaldosBolsas saldosBolsas {
            get {
                return this.saldosBolsasField;
            }
            set {
                this.saldosBolsasField = value;
                this.RaisePropertyChanged("saldosBolsas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerSaldosBolsas", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerSaldosBolsasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasRequest INSaldosBolsasRequest;
        
        public leerSaldosBolsasRequest() {
        }
        
        public leerSaldosBolsasRequest(Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasRequest INSaldosBolsasRequest) {
            this.INSaldosBolsasRequest = INSaldosBolsasRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="leerSaldosBolsasResponse", WrapperNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", IsWrapped=true)]
    public partial class leerSaldosBolsasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
        public Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasResponse INSaldosBolsasResponse;
        
        public leerSaldosBolsasResponse() {
        }
        
        public leerSaldosBolsasResponse(Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasResponse INSaldosBolsasResponse) {
            this.INSaldosBolsasResponse = INSaldosBolsasResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EbsDatosPrepagoV2Channel : Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EbsDatosPrepagoV2Client : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2>, Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2 {
        
        public EbsDatosPrepagoV2Client() {
        }
        
        public EbsDatosPrepagoV2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EbsDatosPrepagoV2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbsDatosPrepagoV2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbsDatosPrepagoV2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoResponse Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2.leerDatosPrepago(Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoRequest request) {
            return base.Channel.leerDatosPrepago(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoResponse leerDatosPrepago(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosPrepagoRequest INDatosPrepagoRequest) {
            Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoRequest inValue = new Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoRequest();
            inValue.INDatosPrepagoRequest = INDatosPrepagoRequest;
            Claro.SIACU.ProxyService.SIACPre.Service2.leerDatosPrepagoResponse retVal = ((Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2)(this)).leerDatosPrepago(inValue);
            return retVal.INDatosPrepagoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionResponse Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2.consultaEstadoSuscripcion(Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionRequest request) {
            return base.Channel.consultaEstadoSuscripcion(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionResponse consultaEstadoSuscripcion(Claro.SIACU.ProxyService.SIACPre.Service2.EstadoSuscripcionRequest EstadoSuscripcionRequest) {
            Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionRequest inValue = new Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionRequest();
            inValue.EstadoSuscripcionRequest = EstadoSuscripcionRequest;
            Claro.SIACU.ProxyService.SIACPre.Service2.consultaEstadoSuscripcionResponse retVal = ((Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2)(this)).consultaEstadoSuscripcion(inValue);
            return retVal.EstadoSuscripcionResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoResponse Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2.leerEstado(Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoRequest request) {
            return base.Channel.leerEstado(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaResponse leerEstado(Claro.SIACU.ProxyService.SIACPre.Service2.INDatosLineaRequest INDatosLineaRequest) {
            Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoRequest inValue = new Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoRequest();
            inValue.INDatosLineaRequest = INDatosLineaRequest;
            Claro.SIACU.ProxyService.SIACPre.Service2.leerEstadoResponse retVal = ((Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2)(this)).leerEstado(inValue);
            return retVal.INDatosLineaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasResponse Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2.leerSaldosBolsas(Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasRequest request) {
            return base.Channel.leerSaldosBolsas(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasResponse leerSaldosBolsas(Claro.SIACU.ProxyService.SIACPre.Service2.INSaldosBolsasRequest INSaldosBolsasRequest) {
            Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasRequest inValue = new Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasRequest();
            inValue.INSaldosBolsasRequest = INSaldosBolsasRequest;
            Claro.SIACU.ProxyService.SIACPre.Service2.leerSaldosBolsasResponse retVal = ((Claro.SIACU.ProxyService.SIACPre.Service2.EbsDatosPrepagoV2)(this)).leerSaldosBolsas(inValue);
            return retVal.INSaldosBolsasResponse;
        }
    }
}
