//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/SOA/service/ConsultaLineaCuentaWS", ConfigurationName="SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType")]
    public interface ConsultaLineaCuentaWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarLineaCuenta no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/SOA/service/ConsultaLineaCuentaWS/consultarLineaCuenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1 consultarLineaCuenta(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/SOA/service/ConsultaLineaCuentaWS/consultarLineaCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1> consultarLineaCuentaAsync(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/SOA/message/consultalineacuentaws")]
    public partial class consultarLineaCuentaRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoConsultaField;
        
        private string valorConsultaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string tipoConsulta {
            get {
                return this.tipoConsultaField;
            }
            set {
                this.tipoConsultaField = value;
                this.RaisePropertyChanged("tipoConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valorConsulta {
            get {
                return this.valorConsultaField;
            }
            set {
                this.valorConsultaField = value;
                this.RaisePropertyChanged("valorConsulta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/SOA/message/consultalineacuentaws")]
    public partial class ItmType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string origenCuentaField;
        
        private string codCuentaField;
        
        private string coIdField;
        
        private string identificacionField;
        
        private string actCuentaProdField;
        
        private string migCuentaProdField;
        
        private string origenRegistroField;
        
        private string estadoField;
        
        private string usrCreaField;
        
        private string usrModifField;
        
        private string fchCreacionField;
        
        private string fchModifField;
        
        private string custCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string origenCuenta {
            get {
                return this.origenCuentaField;
            }
            set {
                this.origenCuentaField = value;
                this.RaisePropertyChanged("origenCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codCuenta {
            get {
                return this.codCuentaField;
            }
            set {
                this.codCuentaField = value;
                this.RaisePropertyChanged("codCuenta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string identificacion {
            get {
                return this.identificacionField;
            }
            set {
                this.identificacionField = value;
                this.RaisePropertyChanged("identificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string actCuentaProd {
            get {
                return this.actCuentaProdField;
            }
            set {
                this.actCuentaProdField = value;
                this.RaisePropertyChanged("actCuentaProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string migCuentaProd {
            get {
                return this.migCuentaProdField;
            }
            set {
                this.migCuentaProdField = value;
                this.RaisePropertyChanged("migCuentaProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string origenRegistro {
            get {
                return this.origenRegistroField;
            }
            set {
                this.origenRegistroField = value;
                this.RaisePropertyChanged("origenRegistro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string usrCrea {
            get {
                return this.usrCreaField;
            }
            set {
                this.usrCreaField = value;
                this.RaisePropertyChanged("usrCrea");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string usrModif {
            get {
                return this.usrModifField;
            }
            set {
                this.usrModifField = value;
                this.RaisePropertyChanged("usrModif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string fchCreacion {
            get {
                return this.fchCreacionField;
            }
            set {
                this.fchCreacionField = value;
                this.RaisePropertyChanged("fchCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string fchModif {
            get {
                return this.fchModifField;
            }
            set {
                this.fchModifField = value;
                this.RaisePropertyChanged("fchModif");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string custCode {
            get {
                return this.custCodeField;
            }
            set {
                this.custCodeField = value;
                this.RaisePropertyChanged("custCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/SOA/message/consultalineacuentaws")]
    public partial class consultarLineaCuentaResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rptaConsultaField;
        
        private ItmType[] cursorDatosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string rptaConsulta {
            get {
                return this.rptaConsultaField;
            }
            set {
                this.rptaConsultaField = value;
                this.RaisePropertyChanged("rptaConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("itm", IsNullable=false)]
        public ItmType[] cursorDatos {
            get {
                return this.cursorDatosField;
            }
            set {
                this.cursorDatosField = value;
                this.RaisePropertyChanged("cursorDatos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarLineaCuentaRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/SOA/message/consultalineacuentaws", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest consultarLineaCuentaRequest;
        
        public consultarLineaCuentaRequest1() {
        }
        
        public consultarLineaCuentaRequest1(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest consultarLineaCuentaRequest) {
            this.consultarLineaCuentaRequest = consultarLineaCuentaRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarLineaCuentaResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/SOA/message/consultalineacuentaws", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse consultarLineaCuentaResponse;
        
        public consultarLineaCuentaResponse1() {
        }
        
        public consultarLineaCuentaResponse1(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse consultarLineaCuentaResponse) {
            this.consultarLineaCuentaResponse = consultarLineaCuentaResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaLineaCuentaWSPortTypeChannel : Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaLineaCuentaWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType>, Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType {
        
        public ConsultaLineaCuentaWSPortTypeClient() {
        }
        
        public ConsultaLineaCuentaWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaLineaCuentaWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaLineaCuentaWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaLineaCuentaWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1 Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType.consultarLineaCuenta(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 request) {
            return base.Channel.consultarLineaCuenta(request);
        }
        
        public Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse consultarLineaCuenta(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest consultarLineaCuentaRequest) {
            Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1();
            inValue.consultarLineaCuentaRequest = consultarLineaCuentaRequest;
            Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1 retVal = ((Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType)(this)).consultarLineaCuenta(inValue);
            return retVal.consultarLineaCuentaResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1> Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType.consultarLineaCuentaAsync(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 request) {
            return base.Channel.consultarLineaCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaResponse1> consultarLineaCuentaAsync(Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest consultarLineaCuentaRequest) {
            Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1 inValue = new Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.consultarLineaCuentaRequest1();
            inValue.consultarLineaCuentaRequest = consultarLineaCuentaRequest;
            return ((Claro.SIACU.ProxyService.SIAC.ConsultaLineaCuenta.ConsultaLineaCuentaWSPortType)(this)).consultarLineaCuentaAsync(inValue);
        }
    }
}
