//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
// 
namespace Claro.SIACU.ProxyService.SIACPost.StateAccount
{
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;


    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaEstadoCuentaSOAP", Namespace="http://claro.com.pe/eai/oac/consultaestadocuenta/")]
    public class ConsultaEstadoCuenta : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ConsultaEstadoCuenta() {
            this.Url = "http://172.19.74.141:8901/OAC_Services/Inquiry/ConsultaEstadoCuenta";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/oac/consultaestadocuenta/consultaEstadoCuenta", RequestNamespace="http://claro.com.pe/eai/oac/consultaestadocuenta/", ResponseNamespace="http://claro.com.pe/eai/oac/consultaestadocuenta/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("audit")]
        public AuditType consultaEstadoCuenta(string txId, string pCodAplicacion, string pUsuarioAplic, string pTipoConsulta, string pTipoServicio, string pCliNroCuenta, string pNroTelefono, string pFlagSoloSaldo, string pFlagSoloDisputa, string pFechaDesde, string pFechaHasta, System.Decimal pTamanoPagina, System.Decimal pNroPagina, [System.Xml.Serialization.XmlArrayItemAttribute("xDetalleEstadoCuentaCab", IsNullable = false)] out DetalleEstadoCuentaCabType[] xEstadoCuenta){
            object[] results = this.Invoke("consultaEstadoCuenta", new object[] {
                        txId,
                        pCodAplicacion,
                        pUsuarioAplic,
                        pTipoConsulta,
                        pTipoServicio,
                        pCliNroCuenta,
                        pNroTelefono,
                        pFlagSoloSaldo,
                        pFlagSoloDisputa,
                        pFechaDesde,
                        pFechaHasta,
                        pTamanoPagina,
                        pNroPagina});
            xEstadoCuenta = ((DetalleEstadoCuentaCabType[])(results[1]));
            return ((AuditType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultaEstadoCuenta(string txId, string pCodAplicacion, string pUsuarioAplic, string pTipoConsulta, string pTipoServicio, string pCliNroCuenta, string pNroTelefono, string pFlagSoloSaldo, string pFlagSoloDisputa, string pFechaDesde, string pFechaHasta, System.Decimal pTamanoPagina, System.Decimal pNroPagina, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaEstadoCuenta", new object[] {
                        txId,
                        pCodAplicacion,
                        pUsuarioAplic,
                        pTipoConsulta,
                        pTipoServicio,
                        pCliNroCuenta,
                        pNroTelefono,
                        pFlagSoloSaldo,
                        pFlagSoloDisputa,
                        pFechaDesde,
                        pFechaHasta,
                        pTamanoPagina,
                        pNroPagina}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuditType EndconsultaEstadoCuenta(System.IAsyncResult asyncResult, out DetalleEstadoCuentaCabType[] xEstadoCuenta) {
            object[] results = this.EndInvoke(asyncResult);
            xEstadoCuenta = ((DetalleEstadoCuentaCabType[])(results[1]));
            return ((AuditType)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/servicecommons/")]
    public class AuditType {
        
        /// <remarks/>
        public string txId;
        
        /// <remarks/>
        public string errorCode;
        
        /// <remarks/>
        public string errorMsg;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/oac/consultaestadocuenta/")]
    public class DetalleEstadoCtaType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTipoDocumento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xNroDocumento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xDescripDocumento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xEstadoDocumento;
        
        /// <remarks/>
        public string xFechaRegistro;
        
        /// <remarks/>
        public string xFechaEmision;
        
        /// <remarks/>
        public string xFechaVencimiento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTipoMoneda;
        
        /// <remarks/>
        public System.Decimal xMontoDocumento;
        
        /// <remarks/>
        public System.Decimal xMontoFco;
        
        /// <remarks/>
        public System.Decimal xMontoFinan;
        
        /// <remarks/>
        public System.Decimal xSaldoDocumento;
        
        /// <remarks/>
        public System.Decimal xSaldoFco;
        
        /// <remarks/>
        public System.Decimal xSaldoFinan;
        
        /// <remarks/>
        public System.Decimal xMontoSoles;
        
        /// <remarks/>
        public System.Decimal xMontoDolares;
        
        /// <remarks/>
        public System.Decimal xCargo;
        
        /// <remarks/>
        public System.Decimal xAbono;
        
        /// <remarks/>
        public System.Decimal xSaldoCuenta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xNroOperacionPago;
        
        /// <remarks/>
        public string xFechaPago;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xFormaPago;
        
        /// <remarks/>
        public System.Decimal xDocAnio;
        
        /// <remarks/>
        public System.Decimal xDocMes;
        
        /// <remarks/>
        public System.Decimal xDocAnioVenc;
        
        /// <remarks/>
        public System.Decimal xDocMesVenc;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xFlagCargoCta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xNroTicket;
        
        /// <remarks/>
        public System.Decimal xMontoReclamado;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTelefono;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xUsuario;
        
        /// <remarks/>
        public string xIdDocOrigen;
        
        /// <remarks/>
        public string xDescripExtend;
        
        /// <remarks/>
        public System.Decimal xIdDocOAC;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/oac/consultaestadocuenta/")]
    public class DetalleEstadoCuentaCabType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xNombreCliente;
        
        /// <remarks/>
        public System.Decimal xDeudaActual;
        
        /// <remarks/>
        public System.Decimal xDeudaVencida;
        
        /// <remarks/>
        public System.Decimal xTotalMontoDisputa;
        
        /// <remarks/>
        public string xFechaUltFactura;
        
        /// <remarks/>
        public string xFechaUtlPago;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xCodCuenta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xCodCuentaAlterna;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xDescUbigeo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTipoCliente;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xEstadoCuenta;
        
        /// <remarks/>
        public string xFechaActivacion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xCicloFacturacion;
        
        /// <remarks/>
        public System.Decimal xLimiteCredito;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xCreditScore;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string xTipoPago;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("xDetalleEstadoCuenta", IsNullable=false)]
        public DetalleEstadoCtaType[] xDetalleTrx;
    }
}
