//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows", ConfigurationName="SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType")]
    public interface BloqDesbloqLineaPostpagoWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarBloDesblo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/consultarBloDesb" +
            "lo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1 consultarBloDesblo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/consultarBloDesb" +
            "lo", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1> consultarBloDesbloAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarBloqueo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/registrarBloqueo" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1 registrarBloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/registrarBloqueo" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1> registrarBloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación registrarDesbloqueo no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/registrarDesbloq" +
            "ueo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1 registrarDesbloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/postventas/bloqdesbloqlineapostpagows/registrarDesbloq" +
            "ueo", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1> registrarDesbloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class consultarBloDesbloRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string coIdField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class curConsultaType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticklerNumberField;
        
        private string ticklerCodeField;
        
        private string ticklerStatusField;
        
        private string createdByField;
        
        private string createdDateField;
        
        private string closeByField;
        
        private string closeDateField;
        
        private string shortDescriptionField;
        
        private string longDescriptionField;
        
        private string estadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ticklerNumber {
            get {
                return this.ticklerNumberField;
            }
            set {
                this.ticklerNumberField = value;
                this.RaisePropertyChanged("ticklerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ticklerCode {
            get {
                return this.ticklerCodeField;
            }
            set {
                this.ticklerCodeField = value;
                this.RaisePropertyChanged("ticklerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ticklerStatus {
            get {
                return this.ticklerStatusField;
            }
            set {
                this.ticklerStatusField = value;
                this.RaisePropertyChanged("ticklerStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string createdBy {
            get {
                return this.createdByField;
            }
            set {
                this.createdByField = value;
                this.RaisePropertyChanged("createdBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
                this.RaisePropertyChanged("createdDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string closeBy {
            get {
                return this.closeByField;
            }
            set {
                this.closeByField = value;
                this.RaisePropertyChanged("closeBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string closeDate {
            get {
                return this.closeDateField;
            }
            set {
                this.closeDateField = value;
                this.RaisePropertyChanged("closeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string shortDescription {
            get {
                return this.shortDescriptionField;
            }
            set {
                this.shortDescriptionField = value;
                this.RaisePropertyChanged("shortDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string longDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
                this.RaisePropertyChanged("longDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class auditResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                this.mensajeRespuestaField = value;
                this.RaisePropertyChanged("mensajeRespuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class parametrosTypeObjetoOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class consultarBloDesbloResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private curConsultaType[] listaCurConsultaField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCurConsulta", Order=1)]
        public curConsultaType[] listaCurConsulta {
            get {
                return this.listaCurConsultaField;
            }
            set {
                this.listaCurConsultaField = value;
                this.RaisePropertyChanged("listaCurConsulta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarBloDesbloRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest consultarBloDesbloRequest;
        
        public consultarBloDesbloRequest1() {
        }
        
        public consultarBloDesbloRequest1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest consultarBloDesbloRequest) {
            this.consultarBloDesbloRequest = consultarBloDesbloRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarBloDesbloResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse consultarBloDesbloResponse;
        
        public consultarBloDesbloResponse1() {
        }
        
        public consultarBloDesbloResponse1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse consultarBloDesbloResponse) {
            this.consultarBloDesbloResponse = consultarBloDesbloResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class registrarBloqueoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string coIdField;
        
        private string ticklerCodeField;
        
        private string longDescField;
        
        private string userField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ticklerCode {
            get {
                return this.ticklerCodeField;
            }
            set {
                this.ticklerCodeField = value;
                this.RaisePropertyChanged("ticklerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string longDesc {
            get {
                return this.longDescField;
            }
            set {
                this.longDescField = value;
                this.RaisePropertyChanged("longDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class registrarBloqueoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarBloqueoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest registrarBloqueoRequest;
        
        public registrarBloqueoRequest1() {
        }
        
        public registrarBloqueoRequest1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest registrarBloqueoRequest) {
            this.registrarBloqueoRequest = registrarBloqueoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarBloqueoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse registrarBloqueoResponse;
        
        public registrarBloqueoResponse1() {
        }
        
        public registrarBloqueoResponse1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse registrarBloqueoResponse) {
            this.registrarBloqueoResponse = registrarBloqueoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class registrarDesbloqueoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditRequestType auditRequestField;
        
        private string coIdField;
        
        private string ticklerCodeField;
        
        private string longDescField;
        
        private string userField;
        
        private parametrosTypeObjetoOpcional[] listaRequestOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditRequestType auditRequest {
            get {
                return this.auditRequestField;
            }
            set {
                this.auditRequestField = value;
                this.RaisePropertyChanged("auditRequest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string coId {
            get {
                return this.coIdField;
            }
            set {
                this.coIdField = value;
                this.RaisePropertyChanged("coId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ticklerCode {
            get {
                return this.ticklerCodeField;
            }
            set {
                this.ticklerCodeField = value;
                this.RaisePropertyChanged("ticklerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string longDesc {
            get {
                return this.longDescField;
            }
            set {
                this.longDescField = value;
                this.RaisePropertyChanged("longDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string user {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
                this.RaisePropertyChanged("user");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types")]
    public partial class registrarDesbloqueoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auditResponseType auditResponseField;
        
        private parametrosTypeObjetoOpcional[] listaResponseOpcionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public auditResponseType auditResponse {
            get {
                return this.auditResponseField;
            }
            set {
                this.auditResponseField = value;
                this.RaisePropertyChanged("auditResponse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public parametrosTypeObjetoOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDesbloqueoRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest registrarDesbloqueoRequest;
        
        public registrarDesbloqueoRequest1() {
        }
        
        public registrarDesbloqueoRequest1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest registrarDesbloqueoRequest) {
            this.registrarDesbloqueoRequest = registrarDesbloqueoRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarDesbloqueoResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/postventa/bloqdesbloqlineapostpagows/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse registrarDesbloqueoResponse;
        
        public registrarDesbloqueoResponse1() {
        }
        
        public registrarDesbloqueoResponse1(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse registrarDesbloqueoResponse) {
            this.registrarDesbloqueoResponse = registrarDesbloqueoResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BloqDesbloqLineaPostpagoWSPortTypeChannel : Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BloqDesbloqLineaPostpagoWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType>, Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType {
        
        public BloqDesbloqLineaPostpagoWSPortTypeClient() {
        }
        
        public BloqDesbloqLineaPostpagoWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BloqDesbloqLineaPostpagoWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloqDesbloqLineaPostpagoWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BloqDesbloqLineaPostpagoWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1 Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.consultarBloDesblo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 request) {
            return base.Channel.consultarBloDesblo(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse consultarBloDesblo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest consultarBloDesbloRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1();
            inValue.consultarBloDesbloRequest = consultarBloDesbloRequest;
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).consultarBloDesblo(inValue);
            return retVal.consultarBloDesbloResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1> Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.consultarBloDesbloAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 request) {
            return base.Channel.consultarBloDesbloAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloResponse1> consultarBloDesbloAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest consultarBloDesbloRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.consultarBloDesbloRequest1();
            inValue.consultarBloDesbloRequest = consultarBloDesbloRequest;
            return ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).consultarBloDesbloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1 Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.registrarBloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 request) {
            return base.Channel.registrarBloqueo(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse registrarBloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest registrarBloqueoRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1();
            inValue.registrarBloqueoRequest = registrarBloqueoRequest;
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).registrarBloqueo(inValue);
            return retVal.registrarBloqueoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1> Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.registrarBloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 request) {
            return base.Channel.registrarBloqueoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoResponse1> registrarBloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest registrarBloqueoRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarBloqueoRequest1();
            inValue.registrarBloqueoRequest = registrarBloqueoRequest;
            return ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).registrarBloqueoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1 Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.registrarDesbloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 request) {
            return base.Channel.registrarDesbloqueo(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse registrarDesbloqueo(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest registrarDesbloqueoRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1();
            inValue.registrarDesbloqueoRequest = registrarDesbloqueoRequest;
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).registrarDesbloqueo(inValue);
            return retVal.registrarDesbloqueoResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1> Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType.registrarDesbloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 request) {
            return base.Channel.registrarDesbloqueoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoResponse1> registrarDesbloqueoAsync(Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest registrarDesbloqueoRequest) {
            Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.registrarDesbloqueoRequest1();
            inValue.registrarDesbloqueoRequest = registrarDesbloqueoRequest;
            return ((Claro.SIACU.ProxyService.SIACPost.BloqDesbloqLineaPostpago.BloqDesbloqLineaPostpagoWSPortType)(this)).registrarDesbloqueoAsync(inValue);
        }
    }
}
