//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPre.PaqueteDatos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/ws", ConfigurationName="SIACPre.PaqueteDatos.EbsPaqueteDatos")]
    public interface EbsPaqueteDatos {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultarPaquetesDisponibles no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/services/paquetedatos/ws/ConsultarPaquetesDisponibles" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse1 ConsultarPaquetesDisponibles(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ComprarPaquetesDatos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/services/paquetedatos/ws/ComprarPaquetesDatos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse1 ComprarPaquetesDatos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ValidarComprarPaquetes no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/services/paquetedatos/ws/ValidarComprarPaquetes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse1 ValidarComprarPaquetes(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ConsultarPaquetesAdquiridos no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/services/paquetedatos/ws/ConsultarPaquetesAdquiridos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse1 ConsultarPaquetesAdquiridos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ConsultarPaquetesDisponiblesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        private string msisdnField;
        
        private string idTipoSuscripcionField;
        
        private string idTipoCompraField;
        
        private ParametroType[] listaRequestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                this.usrAplicacionField = value;
                this.RaisePropertyChanged("usrAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string idTipoSuscripcion {
            get {
                return this.idTipoSuscripcionField;
            }
            set {
                this.idTipoSuscripcionField = value;
                this.RaisePropertyChanged("idTipoSuscripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string idTipoCompra {
            get {
                return this.idTipoCompraField;
            }
            set {
                this.idTipoCompraField = value;
                this.RaisePropertyChanged("idTipoCompra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request")]
        public ParametroType[] listaRequest {
            get {
                return this.listaRequestField;
            }
            set {
                this.listaRequestField = value;
                this.RaisePropertyChanged("listaRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ParametroType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class PaqueteAdquiridoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoConvergenteField;
        
        private string codigoPaqueteField;
        
        private string descripcionField;
        
        private string fechaActivacionField;
        
        private string fechaExpiracionField;
        
        private string canalField;
        
        private string precioField;
        
        private string estadoField;
        
        private string mBComsumidosField;
        
        private string mBDisponiblesField;
        
        private string mBTotalesField;
        
        private string ratingGroupField;
        
        private string zonaField;
        
        private string tipoCompraField;
        
        private ParametroType[] listaPaqueteAdquiridoParametroField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigoConvergente {
            get {
                return this.codigoConvergenteField;
            }
            set {
                this.codigoConvergenteField = value;
                this.RaisePropertyChanged("codigoConvergente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fechaActivacion {
            get {
                return this.fechaActivacionField;
            }
            set {
                this.fechaActivacionField = value;
                this.RaisePropertyChanged("fechaActivacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string fechaExpiracion {
            get {
                return this.fechaExpiracionField;
            }
            set {
                this.fechaExpiracionField = value;
                this.RaisePropertyChanged("fechaExpiracion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MBComsumidos {
            get {
                return this.mBComsumidosField;
            }
            set {
                this.mBComsumidosField = value;
                this.RaisePropertyChanged("MBComsumidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MBDisponibles {
            get {
                return this.mBDisponiblesField;
            }
            set {
                this.mBDisponiblesField = value;
                this.RaisePropertyChanged("MBDisponibles");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MBTotales {
            get {
                return this.mBTotalesField;
            }
            set {
                this.mBTotalesField = value;
                this.RaisePropertyChanged("MBTotales");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RatingGroup {
            get {
                return this.ratingGroupField;
            }
            set {
                this.ratingGroupField = value;
                this.RaisePropertyChanged("RatingGroup");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string zona {
            get {
                return this.zonaField;
            }
            set {
                this.zonaField = value;
                this.RaisePropertyChanged("zona");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string tipoCompra {
            get {
                return this.tipoCompraField;
            }
            set {
                this.tipoCompraField = value;
                this.RaisePropertyChanged("tipoCompra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=14)]
        [System.Xml.Serialization.XmlArrayItemAttribute("parametro")]
        public ParametroType[] listaPaqueteAdquiridoParametro {
            get {
                return this.listaPaqueteAdquiridoParametroField;
            }
            set {
                this.listaPaqueteAdquiridoParametroField = value;
                this.RaisePropertyChanged("listaPaqueteAdquiridoParametro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ComprarPaquete2Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msisdnField;
        
        private string codigoPaqueteField;
        
        private string canalField;
        
        private string idTipoSuscripcionField;
        
        private string idTipoCompraField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string idTipoSuscripcion {
            get {
                return this.idTipoSuscripcionField;
            }
            set {
                this.idTipoSuscripcionField = value;
                this.RaisePropertyChanged("idTipoSuscripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idTipoCompra {
            get {
                return this.idTipoCompraField;
            }
            set {
                this.idTipoCompraField = value;
                this.RaisePropertyChanged("idTipoCompra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ComprarPaquete1Type : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msisdnField;
        
        private string idTipoLineaField;
        
        private string codigoPaqueteField;
        
        private string canalField;
        
        private string idTipoSuscripcionField;
        
        private string idTipoCompraField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTipoLinea {
            get {
                return this.idTipoLineaField;
            }
            set {
                this.idTipoLineaField = value;
                this.RaisePropertyChanged("idTipoLinea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idTipoSuscripcion {
            get {
                return this.idTipoSuscripcionField;
            }
            set {
                this.idTipoSuscripcionField = value;
                this.RaisePropertyChanged("idTipoSuscripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string idTipoCompra {
            get {
                return this.idTipoCompraField;
            }
            set {
                this.idTipoCompraField = value;
                this.RaisePropertyChanged("idTipoCompra");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class PaqueteDisponibleType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aplicacionField;
        
        private string tipoServicioField;
        
        private string tipoSuscripcionField;
        
        private string tipoCompraField;
        
        private string codigoConvergenteField;
        
        private string plataformaField;
        
        private string codigoPaqueteField;
        
        private string descripcionPaqueteField;
        
        private string codigoSMSField;
        
        private string precioField;
        
        private string disponibilidadField;
        
        private string vigenciaField;
        
        private string mbIncluidosField;
        
        private string tipoNegocioField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string tipoServicio {
            get {
                return this.tipoServicioField;
            }
            set {
                this.tipoServicioField = value;
                this.RaisePropertyChanged("tipoServicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string tipoSuscripcion {
            get {
                return this.tipoSuscripcionField;
            }
            set {
                this.tipoSuscripcionField = value;
                this.RaisePropertyChanged("tipoSuscripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string tipoCompra {
            get {
                return this.tipoCompraField;
            }
            set {
                this.tipoCompraField = value;
                this.RaisePropertyChanged("tipoCompra");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string codigoConvergente {
            get {
                return this.codigoConvergenteField;
            }
            set {
                this.codigoConvergenteField = value;
                this.RaisePropertyChanged("codigoConvergente");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string plataforma {
            get {
                return this.plataformaField;
            }
            set {
                this.plataformaField = value;
                this.RaisePropertyChanged("plataforma");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string descripcionPaquete {
            get {
                return this.descripcionPaqueteField;
            }
            set {
                this.descripcionPaqueteField = value;
                this.RaisePropertyChanged("descripcionPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string codigoSMS {
            get {
                return this.codigoSMSField;
            }
            set {
                this.codigoSMSField = value;
                this.RaisePropertyChanged("codigoSMS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string disponibilidad {
            get {
                return this.disponibilidadField;
            }
            set {
                this.disponibilidadField = value;
                this.RaisePropertyChanged("disponibilidad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string vigencia {
            get {
                return this.vigenciaField;
            }
            set {
                this.vigenciaField = value;
                this.RaisePropertyChanged("vigencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string mbIncluidos {
            get {
                return this.mbIncluidosField;
            }
            set {
                this.mbIncluidosField = value;
                this.RaisePropertyChanged("mbIncluidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string tipoNegocio {
            get {
                return this.tipoNegocioField;
            }
            set {
                this.tipoNegocioField = value;
                this.RaisePropertyChanged("tipoNegocio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class AuditType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string txIdField;
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string txId {
            get {
                return this.txIdField;
            }
            set {
                this.txIdField = value;
                this.RaisePropertyChanged("txId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("errorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ConsultarPaquetesDisponiblesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditType auditField;
        
        private PaqueteDisponibleType[] listaPaquetesDisponiblesField;
        
        private ParametroType[] listaResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditType Audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("Audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PaqueteDisponible", IsNullable=false)]
        public PaqueteDisponibleType[] ListaPaquetesDisponibles {
            get {
                return this.listaPaquetesDisponiblesField;
            }
            set {
                this.listaPaquetesDisponiblesField = value;
                this.RaisePropertyChanged("ListaPaquetesDisponibles");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("response")]
        public ParametroType[] listaResponse {
            get {
                return this.listaResponseField;
            }
            set {
                this.listaResponseField = value;
                this.RaisePropertyChanged("listaResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPaquetesDisponiblesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest ConsultarPaquetesDisponiblesRequest;
        
        public ConsultarPaquetesDisponiblesRequest1() {
        }
        
        public ConsultarPaquetesDisponiblesRequest1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest ConsultarPaquetesDisponiblesRequest) {
            this.ConsultarPaquetesDisponiblesRequest = ConsultarPaquetesDisponiblesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPaquetesDisponiblesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse ConsultarPaquetesDisponiblesResponse;
        
        public ConsultarPaquetesDisponiblesResponse1() {
        }
        
        public ConsultarPaquetesDisponiblesResponse1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse ConsultarPaquetesDisponiblesResponse) {
            this.ConsultarPaquetesDisponiblesResponse = ConsultarPaquetesDisponiblesResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ComprarPaquetesDatosRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        private ComprarPaquete1Type comprarPaqueteField;
        
        private ParametroType[] listaRequestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                this.usrAplicacionField = value;
                this.RaisePropertyChanged("usrAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ComprarPaquete1Type comprarPaquete {
            get {
                return this.comprarPaqueteField;
            }
            set {
                this.comprarPaqueteField = value;
                this.RaisePropertyChanged("comprarPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request")]
        public ParametroType[] listaRequest {
            get {
                return this.listaRequestField;
            }
            set {
                this.listaRequestField = value;
                this.RaisePropertyChanged("listaRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ComprarPaquetesDatosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditType auditField;
        
        private ParametroType[] listaResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditType Audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("Audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("response")]
        public ParametroType[] listaResponse {
            get {
                return this.listaResponseField;
            }
            set {
                this.listaResponseField = value;
                this.RaisePropertyChanged("listaResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarPaquetesDatosRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest ComprarPaquetesDatosRequest;
        
        public ComprarPaquetesDatosRequest1() {
        }
        
        public ComprarPaquetesDatosRequest1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest ComprarPaquetesDatosRequest) {
            this.ComprarPaquetesDatosRequest = ComprarPaquetesDatosRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ComprarPaquetesDatosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse ComprarPaquetesDatosResponse;
        
        public ComprarPaquetesDatosResponse1() {
        }
        
        public ComprarPaquetesDatosResponse1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse ComprarPaquetesDatosResponse) {
            this.ComprarPaquetesDatosResponse = ComprarPaquetesDatosResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ValidarComprarPaquetesRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        private ComprarPaquete2Type comprarPaqueteField;
        
        private ParametroType[] listaRequestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                this.usrAplicacionField = value;
                this.RaisePropertyChanged("usrAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ComprarPaquete2Type comprarPaquete {
            get {
                return this.comprarPaqueteField;
            }
            set {
                this.comprarPaqueteField = value;
                this.RaisePropertyChanged("comprarPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request")]
        public ParametroType[] listaRequest {
            get {
                return this.listaRequestField;
            }
            set {
                this.listaRequestField = value;
                this.RaisePropertyChanged("listaRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ValidarComprarPaquetesResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditType auditField;
        
        private ParametroType[] listaResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditType Audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("Audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("response")]
        public ParametroType[] listaResponse {
            get {
                return this.listaResponseField;
            }
            set {
                this.listaResponseField = value;
                this.RaisePropertyChanged("listaResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarComprarPaquetesRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest ValidarComprarPaquetesRequest;
        
        public ValidarComprarPaquetesRequest1() {
        }
        
        public ValidarComprarPaquetesRequest1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest ValidarComprarPaquetesRequest) {
            this.ValidarComprarPaquetesRequest = ValidarComprarPaquetesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarComprarPaquetesResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse ValidarComprarPaquetesResponse;
        
        public ValidarComprarPaquetesResponse1() {
        }
        
        public ValidarComprarPaquetesResponse1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse ValidarComprarPaquetesResponse) {
            this.ValidarComprarPaquetesResponse = ValidarComprarPaquetesResponse;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ConsultarPaquetesAdquiridosRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        private string msisdnField;
        
        private string canalField;
        
        private string codigoPaqueteField;
        
        private string estadoPaqueteField;
        
        private string fechaInicioField;
        
        private string fechaFinField;
        
        private string idTipoLineaField;
        
        private string familiaPaqueteField;
        
        private ParametroType[] listaRequestField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                this.usrAplicacionField = value;
                this.RaisePropertyChanged("usrAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string codigoPaquete {
            get {
                return this.codigoPaqueteField;
            }
            set {
                this.codigoPaqueteField = value;
                this.RaisePropertyChanged("codigoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string estadoPaquete {
            get {
                return this.estadoPaqueteField;
            }
            set {
                this.estadoPaqueteField = value;
                this.RaisePropertyChanged("estadoPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string idTipoLinea {
            get {
                return this.idTipoLineaField;
            }
            set {
                this.idTipoLineaField = value;
                this.RaisePropertyChanged("idTipoLinea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string familiaPaquete {
            get {
                return this.familiaPaqueteField;
            }
            set {
                this.familiaPaqueteField = value;
                this.RaisePropertyChanged("familiaPaquete");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("request")]
        public ParametroType[] listaRequest {
            get {
                return this.listaRequestField;
            }
            set {
                this.listaRequestField = value;
                this.RaisePropertyChanged("listaRequest");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd")]
    public partial class ConsultarPaquetesAdquiridosResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditType auditField;
        
        private PaqueteAdquiridoType[] listaPaquetesAdquiridosField;
        
        private ParametroType[] listaResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditType Audit {
            get {
                return this.auditField;
            }
            set {
                this.auditField = value;
                this.RaisePropertyChanged("Audit");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PaqueteAdquirido", IsNullable=false)]
        public PaqueteAdquiridoType[] ListaPaquetesAdquiridos {
            get {
                return this.listaPaquetesAdquiridosField;
            }
            set {
                this.listaPaquetesAdquiridosField = value;
                this.RaisePropertyChanged("ListaPaquetesAdquiridos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("response")]
        public ParametroType[] listaResponse {
            get {
                return this.listaResponseField;
            }
            set {
                this.listaResponseField = value;
                this.RaisePropertyChanged("listaResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPaquetesAdquiridosRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest ConsultarPaquetesAdquiridosRequest;
        
        public ConsultarPaquetesAdquiridosRequest1() {
        }
        
        public ConsultarPaquetesAdquiridosRequest1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest ConsultarPaquetesAdquiridosRequest) {
            this.ConsultarPaquetesAdquiridosRequest = ConsultarPaquetesAdquiridosRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultarPaquetesAdquiridosResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/services/paquetedatos/xsd", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse ConsultarPaquetesAdquiridosResponse;
        
        public ConsultarPaquetesAdquiridosResponse1() {
        }
        
        public ConsultarPaquetesAdquiridosResponse1(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse ConsultarPaquetesAdquiridosResponse) {
            this.ConsultarPaquetesAdquiridosResponse = ConsultarPaquetesAdquiridosResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EbsPaqueteDatosChannel : Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EbsPaqueteDatosClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos>, Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos {
        
        public EbsPaqueteDatosClient() {
        }
        
        public EbsPaqueteDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EbsPaqueteDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbsPaqueteDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EbsPaqueteDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse1 Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos.ConsultarPaquetesDisponibles(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest1 request) {
            return base.Channel.ConsultarPaquetesDisponibles(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse ConsultarPaquetesDisponibles(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest ConsultarPaquetesDisponiblesRequest) {
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesRequest1();
            inValue.ConsultarPaquetesDisponiblesRequest = ConsultarPaquetesDisponiblesRequest;
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesDisponiblesResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos)(this)).ConsultarPaquetesDisponibles(inValue);
            return retVal.ConsultarPaquetesDisponiblesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse1 Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos.ComprarPaquetesDatos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest1 request) {
            return base.Channel.ComprarPaquetesDatos(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse ComprarPaquetesDatos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest ComprarPaquetesDatosRequest) {
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosRequest1();
            inValue.ComprarPaquetesDatosRequest = ComprarPaquetesDatosRequest;
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ComprarPaquetesDatosResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos)(this)).ComprarPaquetesDatos(inValue);
            return retVal.ComprarPaquetesDatosResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse1 Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos.ValidarComprarPaquetes(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest1 request) {
            return base.Channel.ValidarComprarPaquetes(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse ValidarComprarPaquetes(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest ValidarComprarPaquetesRequest) {
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesRequest1();
            inValue.ValidarComprarPaquetesRequest = ValidarComprarPaquetesRequest;
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ValidarComprarPaquetesResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos)(this)).ValidarComprarPaquetes(inValue);
            return retVal.ValidarComprarPaquetesResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse1 Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos.ConsultarPaquetesAdquiridos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest1 request) {
            return base.Channel.ConsultarPaquetesAdquiridos(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse ConsultarPaquetesAdquiridos(Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest ConsultarPaquetesAdquiridosRequest) {
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosRequest1();
            inValue.ConsultarPaquetesAdquiridosRequest = ConsultarPaquetesAdquiridosRequest;
            Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.ConsultarPaquetesAdquiridosResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPre.PaqueteDatos.EbsPaqueteDatos)(this)).ConsultarPaquetesAdquiridos(inValue);
            return retVal.ConsultarPaquetesAdquiridosResponse;
        }
    }
}
