//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIAC.Claves {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ebs/operaciones/consultaclaves", ConfigurationName="SIAC.Claves.ebsConsultaClavesPortType")]
    public interface ebsConsultaClavesPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/operaciones/consultaclaves/desencriptar", ReplyAction="*")]
        Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse desencriptar(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/operaciones/consultaclaves/desencriptar", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse> desencriptarAsync(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class desencriptarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="desencriptarRequest", Namespace="http://claro.com.pe/eai/ebs/operaciones/consultaclaves", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequestBody Body;
        
        public desencriptarRequest() {
        }
        
        public desencriptarRequest(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://claro.com.pe/eai/ebs/operaciones/consultaclaves")]
    public partial class desencriptarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ipAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ipTransicion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usrAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string idAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string codigoAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string usuarioAplicacionEncriptado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string claveEncriptado;
        
        public desencriptarRequestBody() {
        }
        
        public desencriptarRequestBody(string idTransaccion, string ipAplicacion, string ipTransicion, string usrAplicacion, string idAplicacion, string codigoAplicacion, string usuarioAplicacionEncriptado, string claveEncriptado) {
            this.idTransaccion = idTransaccion;
            this.ipAplicacion = ipAplicacion;
            this.ipTransicion = ipTransicion;
            this.usrAplicacion = usrAplicacion;
            this.idAplicacion = idAplicacion;
            this.codigoAplicacion = codigoAplicacion;
            this.usuarioAplicacionEncriptado = usuarioAplicacionEncriptado;
            this.claveEncriptado = claveEncriptado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class desencriptarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="desencriptarResponse", Namespace="http://claro.com.pe/eai/ebs/operaciones/consultaclaves", Order=0)]
        public Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponseBody Body;
        
        public desencriptarResponse() {
        }
        
        public desencriptarResponse(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://claro.com.pe/eai/ebs/operaciones/consultaclaves")]
    public partial class desencriptarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idTransaccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codigoResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mensajeResultado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usuarioAplicacion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string clave;
        
        public desencriptarResponseBody() {
        }
        
        public desencriptarResponseBody(string idTransaccion, string codigoResultado, string mensajeResultado, string usuarioAplicacion, string clave) {
            this.idTransaccion = idTransaccion;
            this.codigoResultado = codigoResultado;
            this.mensajeResultado = mensajeResultado;
            this.usuarioAplicacion = usuarioAplicacion;
            this.clave = clave;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ebsConsultaClavesPortTypeChannel : Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ebsConsultaClavesPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType>, Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType {
        
        public ebsConsultaClavesPortTypeClient() {
        }
        
        public ebsConsultaClavesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ebsConsultaClavesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebsConsultaClavesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebsConsultaClavesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType.desencriptar(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest request) {
            return base.Channel.desencriptar(request);
        }
        
        public string desencriptar(ref string idTransaccion, string ipAplicacion, string ipTransicion, string usrAplicacion, string idAplicacion, string codigoAplicacion, string usuarioAplicacionEncriptado, string claveEncriptado, out string mensajeResultado, out string usuarioAplicacion, out string clave) {
            Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest inValue = new Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest();
            inValue.Body = new Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequestBody();
            inValue.Body.idTransaccion = idTransaccion;
            inValue.Body.ipAplicacion = ipAplicacion;
            inValue.Body.ipTransicion = ipTransicion;
            inValue.Body.usrAplicacion = usrAplicacion;
            inValue.Body.idAplicacion = idAplicacion;
            inValue.Body.codigoAplicacion = codigoAplicacion;
            inValue.Body.usuarioAplicacionEncriptado = usuarioAplicacionEncriptado;
            inValue.Body.claveEncriptado = claveEncriptado;
            Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse retVal = ((Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType)(this)).desencriptar(inValue);
            idTransaccion = retVal.Body.idTransaccion;
            mensajeResultado = retVal.Body.mensajeResultado;
            usuarioAplicacion = retVal.Body.usuarioAplicacion;
            clave = retVal.Body.clave;
            return retVal.Body.codigoResultado;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse> Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType.desencriptarAsync(Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest request) {
            return base.Channel.desencriptarAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIAC.Claves.desencriptarResponse> desencriptarAsync(string idTransaccion, string ipAplicacion, string ipTransicion, string usrAplicacion, string idAplicacion, string codigoAplicacion, string usuarioAplicacionEncriptado, string claveEncriptado) {
            Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest inValue = new Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequest();
            inValue.Body = new Claro.SIACU.ProxyService.SIAC.Claves.desencriptarRequestBody();
            inValue.Body.idTransaccion = idTransaccion;
            inValue.Body.ipAplicacion = ipAplicacion;
            inValue.Body.ipTransicion = ipTransicion;
            inValue.Body.usrAplicacion = usrAplicacion;
            inValue.Body.idAplicacion = idAplicacion;
            inValue.Body.codigoAplicacion = codigoAplicacion;
            inValue.Body.usuarioAplicacionEncriptado = usuarioAplicacionEncriptado;
            inValue.Body.claveEncriptado = claveEncriptado;
            return ((Claro.SIACU.ProxyService.SIAC.Claves.ebsConsultaClavesPortType)(this)).desencriptarAsync(inValue);
        }
    }
}
