//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPost.IGVHFC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws", ConfigurationName="SIACPost.IGVHFC.ConsultaIGVWSPortType")]
    public interface ConsultaIGVWSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarIGV no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/consultarIGV", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse1 consultarIGV(Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")]
    public partial class consultarIGVRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AuditRequestType auditoriaField;
        
        private string updateCacheField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AuditRequestType auditoria {
            get {
                return this.auditoriaField;
            }
            set {
                this.auditoriaField = value;
                this.RaisePropertyChanged("auditoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string updateCache {
            get {
                return this.updateCacheField;
            }
            set {
                this.updateCacheField = value;
                this.RaisePropertyChanged("updateCache");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class AuditRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string nombreAplicacionField;
        
        private string usuarioAplicacionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                this.ipAplicacionField = value;
                this.RaisePropertyChanged("ipAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string nombreAplicacion {
            get {
                return this.nombreAplicacionField;
            }
            set {
                this.nombreAplicacionField = value;
                this.RaisePropertyChanged("nombreAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public partial class DefaultServiceResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string categoriaField;
        
        private string idRespuestaField;
        
        private string mensajeField;
        
        private string excepcionField;
        
        private string idTransaccionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("idRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string excepcion {
            get {
                return this.excepcionField;
            }
            set {
                this.excepcionField = value;
                this.RaisePropertyChanged("excepcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                this.idTransaccionField = value;
                this.RaisePropertyChanged("idTransaccion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")]
    public partial class ListaIGVSResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imputIdField;
        
        private string impuvDesField;
        
        private double igvField;
        
        private double igvDField;
        
        private string impunTipDocField;
        
        private string impudFecRegistroField;
        
        private string impudFecIniVigenciaField;
        
        private string impudFecFinVigenciaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string imputId {
            get {
                return this.imputIdField;
            }
            set {
                this.imputIdField = value;
                this.RaisePropertyChanged("imputId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string impuvDes {
            get {
                return this.impuvDesField;
            }
            set {
                this.impuvDesField = value;
                this.RaisePropertyChanged("impuvDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double igv {
            get {
                return this.igvField;
            }
            set {
                this.igvField = value;
                this.RaisePropertyChanged("igv");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double igvD {
            get {
                return this.igvDField;
            }
            set {
                this.igvDField = value;
                this.RaisePropertyChanged("igvD");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string impunTipDoc {
            get {
                return this.impunTipDocField;
            }
            set {
                this.impunTipDocField = value;
                this.RaisePropertyChanged("impunTipDoc");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string impudFecRegistro {
            get {
                return this.impudFecRegistroField;
            }
            set {
                this.impudFecRegistroField = value;
                this.RaisePropertyChanged("impudFecRegistro");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string impudFecIniVigencia {
            get {
                return this.impudFecIniVigenciaField;
            }
            set {
                this.impudFecIniVigenciaField = value;
                this.RaisePropertyChanged("impudFecIniVigencia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string impudFecFinVigencia {
            get {
                return this.impudFecFinVigenciaField;
            }
            set {
                this.impudFecFinVigenciaField = value;
                this.RaisePropertyChanged("impudFecFinVigencia");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1532.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types")]
    public partial class consultarIGVResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ListaIGVSResponseType[] listaIGVSField;
        
        private DefaultServiceResponse defaultServiceResponseField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("listaIGVS", Order=0)]
        public ListaIGVSResponseType[] listaIGVS {
            get {
                return this.listaIGVSField;
            }
            set {
                this.listaIGVSField = value;
                this.RaisePropertyChanged("listaIGVS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DefaultServiceResponse defaultServiceResponse {
            get {
                return this.defaultServiceResponseField;
            }
            set {
                this.defaultServiceResponseField = value;
                this.RaisePropertyChanged("defaultServiceResponse");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarIGVRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest consultarIGVRequest;
        
        public consultarIGVRequest1() {
        }
        
        public consultarIGVRequest1(Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest consultarIGVRequest) {
            this.consultarIGVRequest = consultarIGVRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarIGVResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ws/consultaigv/consultaigvws/types", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse consultarIGVResponse;
        
        public consultarIGVResponse1() {
        }
        
        public consultarIGVResponse1(Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse consultarIGVResponse) {
            this.consultarIGVResponse = consultarIGVResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaIGVWSPortTypeChannel : Claro.SIACU.ProxyService.SIACPost.IGVHFC.ConsultaIGVWSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaIGVWSPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPost.IGVHFC.ConsultaIGVWSPortType>, Claro.SIACU.ProxyService.SIACPost.IGVHFC.ConsultaIGVWSPortType {
        
        public ConsultaIGVWSPortTypeClient() {
        }
        
        public ConsultaIGVWSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaIGVWSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaIGVWSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaIGVWSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse1 Claro.SIACU.ProxyService.SIACPost.IGVHFC.ConsultaIGVWSPortType.consultarIGV(Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest1 request) {
            return base.Channel.consultarIGV(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse consultarIGV(Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest consultarIGVRequest) {
            Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest1 inValue = new Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVRequest1();
            inValue.consultarIGVRequest = consultarIGVRequest;
            Claro.SIACU.ProxyService.SIACPost.IGVHFC.consultarIGVResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPost.IGVHFC.ConsultaIGVWSPortType)(this)).consultarIGV(inValue);
            return retVal.consultarIGVResponse;
        }
    }
}
