//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM {
    
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
    public partial class ClaroFaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idAuditoriaField;
        
        private string codigoErrorField;
        
        private string descripcionErrorField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private object errorOrigenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idAuditoria {
            get {
                return this.idAuditoriaField;
            }
            set {
                this.idAuditoriaField = value;
                this.RaisePropertyChanged("idAuditoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoError {
            get {
                return this.codigoErrorField;
            }
            set {
                this.codigoErrorField = value;
                this.RaisePropertyChanged("codigoError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionError {
            get {
                return this.descripcionErrorField;
            }
            set {
                this.descripcionErrorField = value;
                this.RaisePropertyChanged("descripcionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
                this.RaisePropertyChanged("ubicacionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public object errorOrigen {
            get {
                return this.errorOrigenField;
            }
            set {
                this.errorOrigenField = value;
                this.RaisePropertyChanged("errorOrigen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public partial class Detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public partial class Fault : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string faultcodeField;
        
        private string faultstringField;
        
        private string faultactorField;
        
        private Detail detailField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string faultcode {
            get {
                return this.faultcodeField;
            }
            set {
                this.faultcodeField = value;
                this.RaisePropertyChanged("faultcode");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string faultstring {
            get {
                return this.faultstringField;
            }
            set {
                this.faultstringField = value;
                this.RaisePropertyChanged("faultstring");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string faultactor {
            get {
                return this.faultactorField;
            }
            set {
                this.faultactorField = value;
                this.RaisePropertyChanged("faultactor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Detail detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="HeaderResponseType", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    public partial class HeaderResponseType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private string fechaInicioField;

        private string fechaFinField;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
                this.RaisePropertyChanged("idTransaccionESB");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
                this.RaisePropertyChanged("nodoAdicional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="HeaderRequestType", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    public partial class HeaderRequestType1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string canalField;
        
        private string idAplicacionField;

        private bool idAplicacionFieldSpecified;
        
        private string usuarioAplicacionField;
        
        private string usuarioSesionField;
        
        private string idTransaccionESBField;
        
        private string idTransaccionNegocioField;
        
        private string fechaInicioField;

        private bool fechaInicioFieldSpecified;
        
        private object nodoAdicionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string canal {
            get {
                return this.canalField;
            }
            set {
                this.canalField = value;
                this.RaisePropertyChanged("canal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string idAplicacion {
            get {
                return this.idAplicacionField;
            }
            set {
                this.idAplicacionField = value;
                this.RaisePropertyChanged("idAplicacion");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAplicacionSpecified
        {
            get
            {
                return this.idAplicacionFieldSpecified;
            }
            set
            {
                this.idAplicacionFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string usuarioAplicacion {
            get {
                return this.usuarioAplicacionField;
            }
            set {
                this.usuarioAplicacionField = value;
                this.RaisePropertyChanged("usuarioAplicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string usuarioSesion {
            get {
                return this.usuarioSesionField;
            }
            set {
                this.usuarioSesionField = value;
                this.RaisePropertyChanged("usuarioSesion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string idTransaccionESB {
            get {
                return this.idTransaccionESBField;
            }
            set {
                this.idTransaccionESBField = value;
                this.RaisePropertyChanged("idTransaccionESB");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string idTransaccionNegocio {
            get {
                return this.idTransaccionNegocioField;
            }
            set {
                this.idTransaccionNegocioField = value;
                this.RaisePropertyChanged("idTransaccionNegocio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }

        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified
        {
            get
            {
                return this.fechaInicioFieldSpecified;
            }
            set
            {
                this.fechaInicioFieldSpecified = value;
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public object nodoAdicional {
            get {
                return this.nodoAdicionalField;
            }
            set {
                this.nodoAdicionalField = value;
                this.RaisePropertyChanged("nodoAdicional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class StatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string codeField;
        
        private string messageField;
        
        private string msgidField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string msgid {
            get {
                return this.msgidField;
            }
            set {
                this.msgidField = value;
                this.RaisePropertyChanged("msgid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string consumerField;
        
        private string pidField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private ArgType[] varArgField;
        
        private StatusType statusField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public StatusType Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class ArgType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public partial class HeaderRequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string languageField;
        
        private string consumerField;
        
        private string systemField;
        
        private string moduloField;
        
        private string pidField;
        
        private string userIdField;
        
        private string dispositivoField;
        
        private string wsIpField;
        
        private string operationField;
        
        private string timestampField;
        
        private string msgTypeField;
        
        private ArgType[] varArgField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("language");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string consumer {
            get {
                return this.consumerField;
            }
            set {
                this.consumerField = value;
                this.RaisePropertyChanged("consumer");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string system {
            get {
                return this.systemField;
            }
            set {
                this.systemField = value;
                this.RaisePropertyChanged("system");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string modulo {
            get {
                return this.moduloField;
            }
            set {
                this.moduloField = value;
                this.RaisePropertyChanged("modulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string pid {
            get {
                return this.pidField;
            }
            set {
                this.pidField = value;
                this.RaisePropertyChanged("pid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string dispositivo {
            get {
                return this.dispositivoField;
            }
            set {
                this.dispositivoField = value;
                this.RaisePropertyChanged("dispositivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string wsIp {
            get {
                return this.wsIpField;
            }
            set {
                this.wsIpField = value;
                this.RaisePropertyChanged("wsIp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                this.msgTypeField = value;
                this.RaisePropertyChanged("msgType");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg {
            get {
                return this.varArgField;
            }
            set {
                this.varArgField = value;
                this.RaisePropertyChanged("VarArg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/")]
    public partial class DatosSIMType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idLoteField;
        
        private string fechaRegField;
        
        private string iccidField;
        
        private string imsiField;
        
        private string pinField;
        
        private string pukField;
        
        private string pin2Field;
        
        private string puk2Field;
        
        private string admField;
        
        private string cmdCrearField;
        
        private string cmdCreudbField;
        
        private string estadoCodField;
        
        private string estadoDesField;
        
        private string rField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string idLote {
            get {
                return this.idLoteField;
            }
            set {
                this.idLoteField = value;
                this.RaisePropertyChanged("idLote");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string fechaReg {
            get {
                return this.fechaRegField;
            }
            set {
                this.fechaRegField = value;
                this.RaisePropertyChanged("fechaReg");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string iccid {
            get {
                return this.iccidField;
            }
            set {
                this.iccidField = value;
                this.RaisePropertyChanged("iccid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string imsi {
            get {
                return this.imsiField;
            }
            set {
                this.imsiField = value;
                this.RaisePropertyChanged("imsi");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                this.pinField = value;
                this.RaisePropertyChanged("pin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string puk {
            get {
                return this.pukField;
            }
            set {
                this.pukField = value;
                this.RaisePropertyChanged("puk");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string pin2 {
            get {
                return this.pin2Field;
            }
            set {
                this.pin2Field = value;
                this.RaisePropertyChanged("pin2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string puk2 {
            get {
                return this.puk2Field;
            }
            set {
                this.puk2Field = value;
                this.RaisePropertyChanged("puk2");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string adm {
            get {
                return this.admField;
            }
            set {
                this.admField = value;
                this.RaisePropertyChanged("adm");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string cmdCrear {
            get {
                return this.cmdCrearField;
            }
            set {
                this.cmdCrearField = value;
                this.RaisePropertyChanged("cmdCrear");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string cmdCreudb {
            get {
                return this.cmdCreudbField;
            }
            set {
                this.cmdCreudbField = value;
                this.RaisePropertyChanged("cmdCreudb");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string estadoCod {
            get {
                return this.estadoCodField;
            }
            set {
                this.estadoCodField = value;
                this.RaisePropertyChanged("estadoCod");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string estadoDes {
            get {
                return this.estadoDesField;
            }
            set {
                this.estadoDesField = value;
                this.RaisePropertyChanged("estadoDes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
                this.RaisePropertyChanged("r");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/")]
    public partial class ResponseDataconsultarDatosSIM : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DatosSIMType listaDatosSIMField;
        
        private ResponseOpcionalTypeResponseOpcional[] listaResponseOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DatosSIMType listaDatosSIM {
            get {
                return this.listaDatosSIMField;
            }
            set {
                this.listaDatosSIMField = value;
                this.RaisePropertyChanged("listaDatosSIM");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/", IsNullable=false)]
        public ResponseOpcionalTypeResponseOpcional[] listaResponseOpcional {
            get {
                return this.listaResponseOpcionalField;
            }
            set {
                this.listaResponseOpcionalField = value;
                this.RaisePropertyChanged("listaResponseOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class ResponseOpcionalTypeResponseOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class responseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int estadoField;
        
        private string codigoRespuestaField;
        
        private string descripcionRespuestaField;
        
        private string ubicacionErrorField;
        
        private System.DateTime fechaField;
        
        private string origenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
                this.RaisePropertyChanged("codigoRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string descripcionRespuesta {
            get {
                return this.descripcionRespuestaField;
            }
            set {
                this.descripcionRespuestaField = value;
                this.RaisePropertyChanged("descripcionRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ubicacionError {
            get {
                return this.ubicacionErrorField;
            }
            set {
                this.ubicacionErrorField = value;
                this.RaisePropertyChanged("ubicacionError");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string origen {
            get {
                return this.origenField;
            }
            set {
                this.origenField = value;
                this.RaisePropertyChanged("origen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/")]
    public partial class consultaDatosSIMType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string msisdnField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
                this.RaisePropertyChanged("msisdn");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/esb/ventas/bssconsultadatossim/v1/", ConfigurationName="SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort")]
    public interface BSS_ConsultaDatosSIMPort {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultarDatosSIM no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/esb/ventas/bssconsultadatossim/v1/consultarDatosSIM", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.ClaroFaultType), Action="http://claro.com.pe/esb/ventas/bssconsultadatossim/v1/consultarDatosSIM", Name="claroFault", Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Fault))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderResponseType1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderRequestType1))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderRequestType))]
        Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1 consultarDatosSIM(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/esb/ventas/bssconsultadatossim/v1/consultarDatosSIM", ReplyAction="*")]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1> consultarDatosSIMAsync(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/")]
    public partial class consultarDatosSIMRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private consultaDatosSIMType consultaDatosSIMField;
        
        private RequestOpcionalTypeRequestOpcional[] listaRequestOpcionalField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public consultaDatosSIMType consultaDatosSIM {
            get {
                return this.consultaDatosSIMField;
            }
            set {
                this.consultaDatosSIMField = value;
                this.RaisePropertyChanged("consultaDatosSIM");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/", IsNullable=false)]
        public RequestOpcionalTypeRequestOpcional[] listaRequestOpcional {
            get {
                return this.listaRequestOpcionalField;
            }
            set {
                this.listaRequestOpcionalField = value;
                this.RaisePropertyChanged("listaRequestOpcional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/data/generico/baseschema/v1/")]
    public partial class RequestOpcionalTypeRequestOpcional : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string campoField;
        
        private string valorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo {
            get {
                return this.campoField;
            }
            set {
                this.campoField = value;
                this.RaisePropertyChanged("campo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
                this.RaisePropertyChanged("valor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/")]
    public partial class consultarDatosSIMResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private responseStatus responseStatusField;
        
        private ResponseDataconsultarDatosSIM responseDataField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public responseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ResponseDataconsultarDatosSIM responseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
                this.RaisePropertyChanged("responseData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarDatosSIMRequest1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType HeaderRequest;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="headerRequest", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType1 headerRequest1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest consultarDatosSIMRequest;
        
        public consultarDatosSIMRequest1() {
        }
        
        public consultarDatosSIMRequest1(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType1 headerRequest1, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest consultarDatosSIMRequest) {
            this.HeaderRequest = HeaderRequest;
            this.headerRequest1 = headerRequest1;
            this.consultarDatosSIMRequest = consultarDatosSIMRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarDatosSIMResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType HeaderResponse;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="headerResponse", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType1 headerResponse1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/esb/message/bssconsultadatossim/consultarDatosSIM/v1/", Order=0)]
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse consultarDatosSIMResponse;
        
        public consultarDatosSIMResponse1() {
        }
        
        public consultarDatosSIMResponse1(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType HeaderResponse, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType1 headerResponse1, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse consultarDatosSIMResponse) {
            this.HeaderResponse = HeaderResponse;
            this.headerResponse1 = headerResponse1;
            this.consultarDatosSIMResponse = consultarDatosSIMResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BSS_ConsultaDatosSIMPortChannel : Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BSS_ConsultaDatosSIMPortClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort>, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort {
        
        public BSS_ConsultaDatosSIMPortClient() {
        }
        
        public BSS_ConsultaDatosSIMPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BSS_ConsultaDatosSIMPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSS_ConsultaDatosSIMPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BSS_ConsultaDatosSIMPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1 Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort.consultarDatosSIM(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 request) {
            return base.Channel.consultarDatosSIM(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType consultarDatosSIM(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType1 headerRequest1, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest consultarDatosSIMRequest, out Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderResponseType1 headerResponse1, out Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse consultarDatosSIMResponse) {
            Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1();
            inValue.HeaderRequest = HeaderRequest;
            inValue.headerRequest1 = headerRequest1;
            inValue.consultarDatosSIMRequest = consultarDatosSIMRequest;
            Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1 retVal = ((Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort)(this)).consultarDatosSIM(inValue);
            headerResponse1 = retVal.headerResponse1;
            consultarDatosSIMResponse = retVal.consultarDatosSIMResponse;
            return retVal.HeaderResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1> Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort.consultarDatosSIMAsync(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 request) {
            return base.Channel.consultarDatosSIMAsync(request);
        }
        
        public System.Threading.Tasks.Task<Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMResponse1> consultarDatosSIMAsync(Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType HeaderRequest, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.HeaderRequestType1 headerRequest1, Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest consultarDatosSIMRequest) {
            Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1 inValue = new Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.consultarDatosSIMRequest1();
            inValue.HeaderRequest = HeaderRequest;
            inValue.headerRequest1 = headerRequest1;
            inValue.consultarDatosSIMRequest = consultarDatosSIMRequest;
            return ((Claro.SIACU.ProxyService.SIACPre.ConsultarDatosSIM.BSS_ConsultaDatosSIMPort)(this)).consultarDatosSIMAsync(inValue);
        }
    }
}
