namespace Claro.SIACU.Entity.Dashboard.Postpaid.CancelInvoice
{
    public class InteractionPlusType
    {
        public string pNroInteraccion { get; set; }
        public string pInter1 { get; set; }
        public string pInter2 { get; set; }
        public string pInter3 { get; set; }
        public string pInter4 { get; set; }
        public string pInter5 { get; set; }
        public string pInter6 { get; set; }
        public string pInter7 { get; set; }
        public string pInter8 { get; set; }
        public string pInter9 { get; set; }
        public string pInter10 { get; set; }
        public string pInter11 { get; set; }
        public string pInter12 { get; set; }
        public string pInter13 { get; set; }
        public string pInter14 { get; set; }
        public string pInter15 { get; set; }
        public string pInter16 { get; set; }
        public string pInter17 { get; set; }
        public string pInter18 { get; set; }
        public string pInter19 { get; set; }
        public string pInter20 { get; set; }
        public string pInter21 { get; set; }
        public string pInter22 { get; set; }
        public string pInter23 { get; set; }
        public string pInter24 { get; set; }
        public string pInter25 { get; set; }
        public string pInter26 { get; set; }
        public string pInter27 { get; set; }
        public string pInter28 { get; set; }
        public string pInter29 { get; set; }
        public string pInter30 { get; set; }
        public string pPlusInter2Interact { get; set; }
        public string pAdjustmentAmount { get; set; }
        public string pAdjustmentReason { get; set; }
        public string pAddress { get; set; }
        public string pAmountUnit { get; set; }
        public string pBirthday { get; set; }
        public string pClarifyInteraction { get; set; }
        public string pClaroLdn1 { get; set; }
        public string pClaroLdn2 { get; set; }
        public string pClaroLdn3 { get; set; }
        public string pClaroLdn4 { get; set; }
        public string pClarolocal1 { get; set; }
        public string pClarolocal2 { get; set; }
        public string pClarolocal3 { get; set; }
        public string pClarolocal4 { get; set; }
        public string pClarolocal5 { get; set; }
        public string pClarolocal6 { get; set; }
        public string pContactPhone { get; set; }
        public string pDniLegalRep { get; set; }
        public string pDocumentNumber { get; set; }
        public string pEmail { get; set; }
        public string pFirstName { get; set; }
        public string pFixedNumber { get; set; }
        public string pFlagChangeUser { get; set; }
        public string pFlagLegalRep { get; set; }
        public string pFlagOther { get; set; }
        public string pFlagTitular { get; set; }
        public string pImei { get; set; }
        public string pLastName { get; set; }
        public string pLastnameRep { get; set; }
        public string pLdiNumber { get; set; }
        public string pNameLegalRep { get; set; }
        public string pOldClaroLdn1 { get; set; }
        public string pOldClaroLdn2 { get; set; }
        public string pOldClaroLdn3 { get; set; }
        public string pOldClaroLdn4 { get; set; }
        public string pOldClarolocal1 { get; set; }
        public string pOldClarolocal2 { get; set; }
        public string pOldClarolocal3 { get; set; }
        public string pOldClarolocal4 { get; set; }
        public string pOldClarolocal5 { get; set; }
        public string pOldClarolocal6 { get; set; }
        public string pOldDocNumber { get; set; }
        public string pOldFirstName { get; set; }
        public string pOldFixedPhone { get; set; }
        public string pOldLastName { get; set; }
        public string pOldLdiNumber { get; set; }
        public string pOldFixedNumber { get; set; }
        public string pOperationType { get; set; }
        public string pOtherDocNumber { get; set; }
        public string pOtherFirstName { get; set; }
        public string pOtherLastName { get; set; }
        public string pOtherPhone { get; set; }
        public string pPhoneLegalRep { get; set; }
        public string pReferencePhone { get; set; }
        public string pReason { get; set; }
        public string pModel { get; set; }
        public string pLotCode { get; set; }
        public string pFlagRegistered { get; set; }
        public string pRegistrationReason { get; set; }
        public string pClaroNumber { get; set; }
        public string pMonth { get; set; }
        public string pOstNumber { get; set; }
        public string pBasket { get; set; }
        public string pExpireDate { get; set; }
        public string paddress5 { get; set; }
        public string pchargeamount { get; set; }
        public string pcity { get; set; }
        public string pcontactsex { get; set; }
        public string pdepartment { get; set; }
        public string pdistrict { get; set; }
        public string pemailconfirmation { get; set; }
        public string pfax { get; set; }
        public string pflagcharge { get; set; }
        public string pmaritalstatus { get; set; }
        public string poccupation { get; set; }
        public string pposition { get; set; }
        public string preferenceaddress { get; set; }
        public string ptypedocument { get; set; }
        public string pzipcode { get; set; }
        public string pIccid { get; set; }
    }
}
