//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Claro.SIACU.ProxyService.SIACPost.IMR
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="audiTypeRequest", Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR")]
    [System.SerializableAttribute()]
    public partial class audiTypeRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idTransaccionField;
        
        private string ipAplicacionField;
        
        private string aplicacionField;
        
        private string usrAplicacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.idTransaccionField, value) != true)) {
                    this.idTransaccionField = value;
                    this.RaisePropertyChanged("idTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ipAplicacion {
            get {
                return this.ipAplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.ipAplicacionField, value) != true)) {
                    this.ipAplicacionField = value;
                    this.RaisePropertyChanged("ipAplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.aplicacionField, value) != true)) {
                    this.aplicacionField = value;
                    this.RaisePropertyChanged("aplicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string usrAplicacion {
            get {
                return this.usrAplicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.usrAplicacionField, value) != true)) {
                    this.usrAplicacionField = value;
                    this.RaisePropertyChanged("usrAplicacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="audiTypeResponse", Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR")]
    [System.SerializableAttribute()]
    public partial class audiTypeResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string idTransaccionField;
        
        private string codigoRespuestaField;
        
        private string mensajeRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string idTransaccion {
            get {
                return this.idTransaccionField;
            }
            set {
                if ((object.ReferenceEquals(this.idTransaccionField, value) != true)) {
                    this.idTransaccionField = value;
                    this.RaisePropertyChanged("idTransaccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.codigoRespuestaField, value) != true)) {
                    this.codigoRespuestaField = value;
                    this.RaisePropertyChanged("codigoRespuesta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string mensajeRespuesta {
            get {
                return this.mensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.mensajeRespuestaField, value) != true)) {
                    this.mensajeRespuestaField = value;
                    this.RaisePropertyChanged("mensajeRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", ConfigurationName="SIACPost.IMR.ebsConsultaIMRPortType")]
    public interface ebsConsultaIMRPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de contenedor (consultaIMRRequest) del mensaje consultaIMRRequest no coincide con el valor predeterminado (consultaIMR)
        [System.ServiceModel.OperationContractAttribute(Action="http://claro.com.pe/eai/ebs/ws/ConsultaIMR/ConsultaIMR", ReplyAction="*")]
        Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRResponse consultaIMR(Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaIMRRequest", WrapperNamespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", IsWrapped=true)]
    public partial class consultaIMRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeRequest audit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=1)]
        public string msisdn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=2)]
        public string customerId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=3)]
        public string cuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=4)]
        public int cicloFacturacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=5)]
        public string tipoProducto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=6)]
        public string tipoCliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=7)]
        public string segmento;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=8)]
        public string co_id;
        
        public consultaIMRRequest() {
        }
        
        public consultaIMRRequest(Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeRequest audit, string msisdn, string customerId, string cuenta, int cicloFacturacion, string tipoProducto, string tipoCliente, string segmento, string co_id) {
            this.audit = audit;
            this.msisdn = msisdn;
            this.customerId = customerId;
            this.cuenta = cuenta;
            this.cicloFacturacion = cicloFacturacion;
            this.tipoProducto = tipoProducto;
            this.tipoCliente = tipoCliente;
            this.segmento = segmento;
            this.co_id = co_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultaIMRResponse", WrapperNamespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", IsWrapped=true)]
    public partial class consultaIMRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=0)]
        public Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeResponse audit;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=1)]
        public string montoIMRTotal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=2)]
        public string montoIMR;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://claro.com.pe/eai/ebs/ws/ConsultaIMR", Order=3)]
        public string fechaExpiracion;
        
        public consultaIMRResponse() {
        }
        
        public consultaIMRResponse(Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeResponse audit, string montoIMRTotal, string montoIMR, string fechaExpiracion) {
            this.audit = audit;
            this.montoIMRTotal = montoIMRTotal;
            this.montoIMR = montoIMR;
            this.fechaExpiracion = fechaExpiracion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ebsConsultaIMRPortTypeChannel : Claro.SIACU.ProxyService.SIACPost.IMR.ebsConsultaIMRPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ebsConsultaIMRPortTypeClient : System.ServiceModel.ClientBase<Claro.SIACU.ProxyService.SIACPost.IMR.ebsConsultaIMRPortType>, Claro.SIACU.ProxyService.SIACPost.IMR.ebsConsultaIMRPortType {
        
        public ebsConsultaIMRPortTypeClient() {
        }
        
        public ebsConsultaIMRPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ebsConsultaIMRPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebsConsultaIMRPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ebsConsultaIMRPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRResponse Claro.SIACU.ProxyService.SIACPost.IMR.ebsConsultaIMRPortType.consultaIMR(Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRRequest request) {
            return base.Channel.consultaIMR(request);
        }
        
        public Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeResponse consultaIMR(Claro.SIACU.ProxyService.SIACPost.IMR.audiTypeRequest audit, string msisdn, string customerId, string cuenta, int cicloFacturacion, string tipoProducto, string tipoCliente, string segmento, string co_id, out string montoIMRTotal, out string montoIMR, out string fechaExpiracion) {
            Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRRequest inValue = new Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRRequest();
            inValue.audit = audit;
            inValue.msisdn = msisdn;
            inValue.customerId = customerId;
            inValue.cuenta = cuenta;
            inValue.cicloFacturacion = cicloFacturacion;
            inValue.tipoProducto = tipoProducto;
            inValue.tipoCliente = tipoCliente;
            inValue.segmento = segmento;
            inValue.co_id = co_id;
            Claro.SIACU.ProxyService.SIACPost.IMR.consultaIMRResponse retVal = ((Claro.SIACU.ProxyService.SIACPost.IMR.ebsConsultaIMRPortType)(this)).consultaIMR(inValue);
            montoIMRTotal = retVal.montoIMRTotal;
            montoIMR = retVal.montoIMR;
            fechaExpiracion = retVal.fechaExpiracion;
            return retVal.audit;
        }
    }
}
